### ISSUE TITLE
rkyv build issues with no_std after "std" feature were added for ptr_meta 1.3

### ISSUE THREAD

**Issue by longtomjr** [rkyv/rkyv#141]
Not sure if this is a ptr_meta or rkyv issue. Also, the ptr_meta version published on crates.io seems to be a later version of ptr_meta than the current git repository (at https://github.com/djkoloski/ptr_meta).

I am replacing std with a seperate crate, and get the following issue when trying to build:
```
error: duplicate lang item in crate `std` (which `ptr_meta` depends on): `f32_runtime`.
````
Please let me know if you need any more info.

**Comment by djkoloski** [comment]
A `std` feature was recently added to `ptr_meta`, so I updated rkyv's dependencies to turn off that feature when std is not specified. Could you update to rkyv 0.6.6 and try again?

**Comment by longtomjr** [comment]
Updated to the 0.6.6 and it fixed the issue. Thanks a lot!
