### ISSUE TITLE
Missing Debug impls for many types

### ISSUE THREAD

**Issue by Kixiron** [rkyv/rkyv#173]
Related to #170

A bunch of types are missing debug implementations, namely
- `CompositeSerializer`
- `DefaultValidator`
- `ArchiveValidator`
- `PrefixRange`
- `SharedValidator`
- `SuffixRange`
- Pretty much everything in `rkyv::ser::serializers`

**Comment by djkoloski** [comment]
Related to #170

**Comment by djkoloski** [comment]
Fixed by 964aef7a99d1d5310e3def6cf0e51bd163162cad
