### ISSUE TITLE
rkyv: test failed on s390x and armv7hl

### ISSUE THREAD

**Issue by remilauzier** [rkyv/rkyv#183]
Hi! Test failed on fedora koji. The latest version was used.
https://kojipkgs.fedoraproject.org//work/tasks/2677/73362677/build.log
https://kojipkgs.fedoraproject.org//work/tasks/2672/73362672/build.log

failures:
---- src/with/mod.rs - with::Atomic (line 286) stdout ----
error[E0277]: the trait bound `Atomic: ArchiveWith<AtomicU32>` is not satisfied
 --> src/with/mod.rs:290:10
  |
7 | #[derive(Archive)]
  |          ^^^^^^^ the trait `ArchiveWith<AtomicU32>` is not implemented for `Atomic`
  |
  = note: required because of the requirements on the impl of `Archive` for `With<AtomicU32, Atomic>`
  = help: see issue #48214
  = help: add `#![feature(trivial_bounds)]` to the crate attributes to enable
  = note: this error originates in the derive macro `Archive` (in Nightly builds, run with -Z macro-backtrace for more info)
error: aborting due to previous error

**Comment by djkoloski** [comment]
Fixed by 1c88a82cb1a5eff3576ef11aaab86fbf95d39812, and released in 0.7.6. Please reopen this issue or file a new one if you run into any other problems. 🙂

**Comment by remilauzier** [comment]
Test work! thanks.
