### ISSUE TITLE
Archive not implemented for &'static str

### ISSUE THREAD

**Issue by dvc94ch** [rkyv/rkyv#193]
I guess this would be nice, I'll just use String for now.

**Comment by djkoloski** [comment]
It's not exactly the same semantics, but you can use `#[with(rkyv::with::Boxed)]` to do something similar.

**Comment by dvc94ch** [comment]
it's a hashmap with &'static str keys, probably a bit of a weird use case.

**Comment by dvc94ch** [comment]
Using String doesn't seem to work either: 
```
overflow evaluating the requirement `HashMap<String, Schema>: Archive`
```

**Comment by dvc94ch** [comment]
ah the problem is with recursive data structures:

```rust
pub enum Tree {
    Leaf,
    Tree(Box<Tree>, Box<Tree>),
}
```

**Comment by djkoloski** [comment]
Ah, container types are definitely a bit difficult because they don't cooperate well with wrappers. You can use a newtype pattern to get it to work, even though it's not ideal:

```rust
use rkyv::{Archive, Serialize, with::Boxed};

#[derive(Archive, Serialize)]
pub struct MyStr {
    #[with(Boxed)]
    value:  &'static str,
}

// Also need to impl Hash and Eq for ArchivedMyStr

#[derive(Archive, Serialize)]
pub struct Schema {
    map: HashMap<MyStr, Schema>,
}
```

Recursive structures are supported, but they need a little markup to help the compiler. The [derive macro docs](https://docs.rs/rkyv/0.7.14/rkyv/derive.Archive.html#recursive-types) has a section on serializing recursive types that you may find helpful. There's also a [worked JSON example](https://github.com/rkyv/rkyv/blob/master/examples/json/src/main.rs#L9) in the `examples` directory.

**Comment by dvc94ch** [comment]
fantastic! thanks for your help.

**Comment by dvc94ch** [comment]
One more question. So I have something resembling the json example and a schema that describes the structure in terms of the json data model. How would I go about traversing it dynamically? I'm trying to implement something like this:

```rust
pub struct Ptr<'a> {
    ptr: *const (),
    schema: &'a ArchivedSchema,
}

impl<'a> Ptr<'a> {
    fn value(&self) -> Option<&PrimitiveValue> {
        None
    }

    fn idx(&self, idx: usize) -> Option<Ptr<'a>> {
        if let ArchivedSchema::Array(_, m) = self.schema {
            // ptr is ArchivedVec<T>
            todo!()
        } else {
            None
        }
    }

    fn get(&self, key: &str) -> Option<Ptr<'a>> {
        if let ArchivedSchema::Object(m) = self.schema {
            // ptr is an archived struct
            todo!()
        } else {
            None
        }
    }

    fn len(&self) -> Option<usize> {
        if let ArchivedSchema::Array(_, m) = self.schema {
            // ptr is ArchivedVec<T>
            todo!()
        } else {
            None
        }
    }

    fn keys(&self) -> Option<impl Iterator<Item = &str>> {
        if let ArchivedSchema::Object(m) = self.schema {
            Some(m.keys().map(|k| k.as_str()))
        } else {
            None
        }
    }
}
```
to use like this:
```rust
    let mut doc = Doc::default();
    doc.shopping.push("cheese".into());
    doc.shopping.push("eggs".into());
    doc.shopping.push("milk".into());

    let mut ser = AllocSerializer::<256>::default();
    ser.serialize_value(&doc).unwrap();
    let doc = ser.into_serializer().into_inner().to_vec();
    let mut doc = unsafe { archived_root::<Doc>(&doc[..]) };

    let schema = doc.schema();
    let ptr = doc.ptr(&schema);

    assert_eq!(ptr.keys().unwrap().collect::<Vec<_>>(), vec!["shopping"]);
    let shopping = ptr.get("shopping").unwrap();
    assert_eq!(shopping.len().unwrap(), 3);
    let cheese = shopping.idx(0).unwrap();
    //assert_eq!(cheese.value().unwrap());
    //assert_eq!(cheese.value().unwrap());
```

any help would be very appreciated.

**Comment by djkoloski** [comment]
In this example, is `Doc` a specific struct (with a `shopping` field) or a generic struct (like `JsonValue` in the example)? If it's the former, would the schema store information like field offsets? I think you could use `memoffset` or just manually `ptr.cast::<u8>().add(offset).cast::<()>()` to move your pointer around. You could also use `ptr::addr_of!` if you have type information available.

**Comment by dvc94ch** [comment]
thanks! I'll play around with it some more tomorrow. The `Doc` will be generated somewhat like this:
```
gen_structs!(Doc, vec![
    Make(Kind::Object),
    AddProperty("shopping"),
    LensIn("shopping", Make(Kind::Array)),
    LensIn("shopping", LensMap(Make(Kind::String))),
])
```
so `Doc` would be a generated struct with a set of fields. when we release a new version we can add to the list of lenses, and attach those to the event that was produced. as long as schema transformations are restricted to lenses (bi-directional transformations) we can remain forwards/backwards compatible with other versions of our software. (since it's a decentralized system we have no way of coordinating updates).

**Comment by djkoloski** [comment]
Ah, sounds very interesting! I think it might be similar to [protoss](https://github.com/djkoloski/protoss), which is still unfortunately in development for the foreseeable future. Maybe some ideas from it could help you out!

**Comment by dvc94ch** [comment]
if you're interested there is a formal specification [here](https://github.com/Actyx/cambria) and proofs that the transformations on schemas are reversible and the transformations on values preserves the validity when transforming from one schema to another.

I guess this means I need to be able to compute the struct layout given a schema without additional information. Looking into this (struct layout doesn't seem to be too hard), the alignment of types is architecture specific. It seems that rkyv would suffer the same problem when reading data encoded on a different architecture?

**Comment by dvc94ch** [comment]
so https://github.com/actyx/cambria is complete. still need thorough testing (it's not been tested outside of the working example), but should be ready for experimentation.
