### ISSUE TITLE
Switch feature resolver to version 2

### ISSUE THREAD

**Issue by djkoloski** [rkyv/rkyv#199]
Because of the heavy use of features and complicated interactions between them, switching to feature resolver 2 will help alleviate some common pain points.

**Comment by djkoloski** [comment]
Looks like most of this is actually blocked on https://github.com/rust-lang/cargo/issues/8832. We'll have to wait for this to stabilize.

**Comment by Enter-tainer** [comment]
It seems that [that issue](https://github.com/rust-lang/cargo/issues/8832) is closed now. Will we update to resolve v2 some day?

**Comment by djkoloski** [comment]
The workspace TOML now uses `resolver = "2"`.
