### ISSUE TITLE
Optional support for smallvec

### ISSUE THREAD

**Issue by rklaehn** [rkyv/rkyv#207]
It would be cool if there was a feature flag for providing rkyv support for the very popular smallvec crate ( https://crates.io/crates/smallvec ).

I saw that tinyvec is already supported, but smallvec I think is more popular and has some advantages, such as that the element type does not have to impl Default.

**Comment by djkoloski** [comment]
This seems reasonable, I'll take a look at getting this done.

**Comment by djkoloski** [comment]
Fixed by fd4e54c93a36ea0af0c032eb65cdda474cdab2bc, this will be in the next release.

**Comment by rklaehn** [comment]
That was fast. Thanks!
