### ISSUE TITLE
Serialization of large buffers gets really slow

### ISSUE THREAD

**Issue by rklaehn** [rkyv/rkyv#209]
I was wondering what happens if you serialize an usize that is >32 bit when archived usize is 32 bit (the default). So I wrote a test program that allocates a large byte buffer and tries to serialize it.

Initially I thought it was broken, but it seems that serialization just becomes _really_ slow with large buffers. It properly errors out as soon as the buffer is larger than 4 gig.

Test program:
```rust
fn size_test() {
    for i in 1..33 {
        let n = 1usize<<i;

        println!("--------");
        println!("creating Vec<u8> with size 1<<{}", i);
        let t0 = Instant::now();
        let large = vec![0u8; n];
        println!("done allocating Vec<u8> with size 1<<{} in {}s", i, t0.elapsed().as_secs_f64());

        let t0 = Instant::now();
        let mut serializer = AllocSerializer::<256>::default();
        println!("serializing Vec<u8> with size 1<<{}", i);
        serializer.serialize_value(&large).unwrap();
        println!("done serializing Vec<u8> with size 1<<{} in {}s", i, t0.elapsed().as_secs_f64());

        println!("");
    }
}
```

Results:
```
--------
creating Vec<u8> with size 1<<1
done allocating Vec<u8> with size 1<<1 in 0.000000271s
serializing Vec<u8> with size 1<<1
done serializing Vec<u8> with size 1<<1 in 0.000001904s

--------
creating Vec<u8> with size 1<<2
done allocating Vec<u8> with size 1<<2 in 0.00000008s
serializing Vec<u8> with size 1<<2
done serializing Vec<u8> with size 1<<2 in 0.000001543s

....

--------
creating Vec<u8> with size 1<<30
done allocating Vec<u8> with size 1<<30 in 0.000013375s
serializing Vec<u8> with size 1<<30
done serializing Vec<u8> with size 1<<30 in 2.708035701s

--------
creating Vec<u8> with size 1<<31
done allocating Vec<u8> with size 1<<31 in 0.00001566s
serializing Vec<u8> with size 1<<31
done serializing Vec<u8> with size 1<<31 in 5.383209546s

--------
creating Vec<u8> with size 1<<32
done allocating Vec<u8> with size 1<<32 in 0.000015169s
serializing Vec<u8> with size 1<<32
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExceedsStorageRange', /home/rklaehn/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.18/src/rel_ptr/mod.rs:300:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So serialization of large Vec<u8> gets *REALLY* slow even in release mode. You would expect it to be at least at the same order of magnitude (a bit slower) than allocating the large buffer in the first place. But it is *much* slower than that.

Now, am I doing something wrong, is there something that can be tweaked with the AllocSerializer?

Edit: ran this on linux x64

**Comment by djkoloski** [comment]
I'll take a look at this particular use case and see if there's anything funny going on. This is likely a limitation of running rkyv on stable, but you can get your speed back on nightly!

Could you enable the `copy` feature on nightly and rerun the test? This enables some optimizations using `min_specialization` and auto traits that gives a large performance boost on `memcpy`-able raw data. The relevant benchmark is the [`mesh` benchmark](https://github.com/djkoloski/rust_serialization_benchmark#mesh), which experiences a ~60% reduction in serialization time with the `copy` feature enabled.

**Comment by rklaehn** [comment]
I think usize being 32 bit works fine for my use case. I just wanted to check that it properly catches if an usize is too big, or panics or has undefined behaviour.

**Comment by rklaehn** [comment]
So, here is my test program on nightly, without the `copy` feature:

```
...
serializing Vec<u8> with size 1<<31
done serializing Vec<u8> with size 1<<31 in 6.042306977s
...
```

and here with `copy`:
```
...
serializing Vec<u8> with size 1<<31
done serializing Vec<u8> with size 1<<31 in 0.67156901s
...
```

So it does make things significantly faster.

**Comment by djkoloski** [comment]
Better! It might also be able to get back some performance by pre-sizing the destination buffer. This should be possible by manually constructing your serializer with an `AlignedVec` constructed using `with_capacity`.

**Comment by djkoloski** [comment]
I dug into this a bit more and was able to get some better results. Here is the code I tested with:
```rust
use std::time::Instant;
use rkyv::{
    ser::{serializers::{AlignedSerializer, AllocSerializer}, Serializer},
    util::AlignedVec,
};

fn main() {
    for i in 1..33 {
        let n = 1usize<<i;

        println!("--------");
        println!("creating Vec<u8> with size 1<<{}", i);

        let t0 = Instant::now();
        let large = vec![0u8; n];
        println!("done allocating Vec<u8> with size 1<<{} in {}s", i, t0.elapsed().as_secs_f64());

        let t0 = Instant::now();
        let clone = large.clone();
        println!("done cloning Vec<u8> with size 1<<{} in {}s", i, t0.elapsed().as_secs_f64());

        let t0 = Instant::now();
        let mut serializer = AllocSerializer::<256>::new(
            AlignedSerializer::new(AlignedVec::with_capacity((1usize << i) + 16)),
            Default::default(),
            Default::default(),
        );
        serializer.serialize_value(&large).unwrap();
        println!("done serializing Vec<u8> with size 1<<{} in {}s", i, t0.elapsed().as_secs_f64());

        println!("");
    }
}
```
On nightly with the `copy` feature enabled, these were the numbers I got:
```
creating Vec<u8> with size 1<<28
done allocating Vec<u8> with size 1<<28 in 0.0000293s
done cloning Vec<u8> with size 1<<28 in 0.1058844s
done serializing Vec<u8> with size 1<<28 in 0.0604238s

--------
creating Vec<u8> with size 1<<29
done allocating Vec<u8> with size 1<<29 in 0.0000631s
done cloning Vec<u8> with size 1<<29 in 0.2176155s
done serializing Vec<u8> with size 1<<29 in 0.1152716s

--------
creating Vec<u8> with size 1<<30
done allocating Vec<u8> with size 1<<30 in 0.0000274s
done cloning Vec<u8> with size 1<<30 in 0.3851697s
done serializing Vec<u8> with size 1<<30 in 0.2622459s

--------
creating Vec<u8> with size 1<<31
done allocating Vec<u8> with size 1<<31 in 0.0000336s
done cloning Vec<u8> with size 1<<31 in 0.7848927s
done serializing Vec<u8> with size 1<<31 in 0.5307517s

--------
creating Vec<u8> with size 1<<32
done allocating Vec<u8> with size 1<<32 in 0.0000579s
done cloning Vec<u8> with size 1<<32 in 1.6544371s
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ExceedsStorageRange'
```
You may notice that, oddly, serializing is actually faster than cloning in this case. By comparison, allocating a large array of zeroed bytes is a very fast operation that we can't really bench serialization against.

With that done, I'm going to close this issue. I think it would be valuable to add a copy optimizing wrapper type for vectors though, so I'll file an issue for that. This will enable the same performance on stable by adding something like `#[with(CopyOptimize)]`.

Issue here: https://github.com/rkyv/rkyv/issues/210
