### ISSUE TITLE
Unaligned Buffer, only in Debug mode

### ISSUE THREAD

**Issue by LLBlumire** [rkyv/rkyv#218]
We have generated and stored a large data structure using rkyv.

```rust
let mut serializer = AllocSerializer::<4096>::default();
serializer.serialize_value(&data).unwrap();
let buf = serializer.into_serializer().into_inner();
file.write_all(&buf).await?;
```

Then when deserializing it with  

```rust
unsafe { archived_root::<$proto>(&include_bytes!(location)[..]) }
```

If we do this in debug mode we get the following panic:

```
assertion failed: `(left == right)`
  left: `2`,
 right: `0`: unaligned buffer, expected alignment 8 but found alignment 4
```

This assert is a `debug_assert`, so if we compile it in release mode, we get no panic **BUT**  as far as we can tell the data is being deserialized correctly and is usable without errors or data consistency issues.

The assertion seems to be checking for pointer alignment of some kind, as it all seems fine in release the alignment issue being reported by the debug assert seems strange to me.

How best can we investigate this further?

**Comment by yusdacra** [comment]
Sorry for necroing the issue, but I seem to have hit the same error. It works fine with debug assertions disabled:
```
thread 'tokio-runtime-worker' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `0`: unaligned buffer, expected alignment 4 but found alignment 4', /home/patriot/.cargo/registry/src/github.com-1ecc6299db9ec823/rkyv-0.7.26/src/util/mod.rs:34:5
```
It's not a problem on release but it's annoying when trying to test in debug profile, how would i fix this? FYI here is how I use rkyv:
```rust
let (_, invite_raw) = data.split_at(size_of::<u64>());
let archive = rkyv_arch::<Invite>(invite_raw);
unsafe { archive.deserialize(&mut rkyv::Infallible).unwrap_unchecked() }
```

I tried creating an AlignedVec from the data (`invite_raw`) but that didn't do anything.

**Comment by djkoloski** [comment]
That debug message appears wrong (it should read `expected alignment 4 but found alignment 2`), so I'll get that fixed (issue #230). The actual test is correct though, and the buffer being passed in is only 2-aligned when its contents need 4-alignment or greater. Because you're splitting `data` on an 8-byte boundary, this suggests that `data` itself is only 2-byte aligned. Could you provide some more information about how you're reading in your bytes?

**Comment by yusdacra** [comment]
> Could you provide some more information about how you're reading in your bytes?

The bytes come from https://github.com/spacejam/sled, a database. It returns data as an `IVec`, which is implemented here https://github.com/spacejam/sled/blob/main/src/ivec.rs.

> It could still be a problem in release though.

It deserializes fine so i'm not sure if there is any problems :sweat_smile:

**Comment by djkoloski** [comment]
Hmm, that code suggests that sled should be returning `IVec`s with contents that are always aligned to 8-byte boundaries. Is `data` the whole slice from the `IVec`, or is it a subsection? That subsection needs to also be 4-aligned for your use case. You can print the address of `data` with `println!("data: {:p}", data)` to check whether it's 4-byte aligned (ends in a `0`).

**Comment by yusdacra** [comment]
> Hmm, that code suggests that sled should be returning `IVec`s with contents that are always aligned to 8-byte boundaries. Is `data` the whole slice from the `IVec`, or is it a subsection? That subsection needs to also be 4-aligned for your use case. You can print the address of `data` with `println!("data: {:p}", data)` to check whether it's 4-byte aligned (ends in a `0`).

I think the issue could be that i have a wrapper enum type that wraps an IVec (and a normal Vec). It isn't aligned with `repr` so maybe that is the issue? Otherwise the full slice is used directly from the IVec variant via deref.

**Comment by djkoloski** [comment]
It could be that `Vec<u8>` variant that's causing this behavior, since `Vec` allocates its contents according to their alignment (1 for `u8`). You should be able to swap that out for [`AlignedVec`](https://docs.rs/rkyv/0.7.26/rkyv/util/struct.AlignedVec.html), which stores bytes with 16-alignment.

If you can share some code directly, I can take a look and see if I can help. You're also welcome to jump in [the discord](https://discord.gg/65F6MdnbQh) to get some direct help too. 🙂

**Comment by Chaoses-Ib** [comment]
Unfortunately, the value I read from RocksDB is not aligned and RocksDB doesn't seem to have an option for memory alignment. Can I remove this check if my program only runs on x86-64 and doesn't care about the performance penalty of unalignment?

```rust
let mut iter = db.raw_iterator();
iter.seek_to_first();
while iter.valid() {
    let b = iter.value().unwrap();
    println!("data: {:p}", b);
    let v = unsafe { rkyv::archived_root::<Self>(b) }.deserialize(&mut Infallible).unwrap()
    iter.next();
}
```
```
data: 0x23d92c2726f
thread 'test' panicked at 'assertion failed: `(left == right)`
  left: `3`,
 right: `0`: unaligned buffer, expected alignment 4 but found alignment 1
help: rkyv requires byte buffers to be aligned to access the data inside.
      Using an ALignedVec or manually aligning your data with #[align(...)]
      may resolve this issue.',
```

**Comment by djkoloski** [comment]
Hm, I see. If you're really certain that you won't suffer from undefined behavior, then you can do the same thing as `archived_root` with basically the same code:

```rust
#[inline]
pub unsafe fn archived_root<T: Archive + ?Sized>(bytes: &[u8]) -> &T::Archived {
    archived_value::<T>(bytes, bytes.len() - mem::size_of::<T::Archived>())
}

#[inline]
pub unsafe fn archived_value<T: Archive + ?Sized>(bytes: &[u8], pos: usize) -> &T::Archived {
    // This was the check
    // #[cfg(debug_assertions)]
    // check_alignment::<T::Archived>(bytes.as_ptr());

    &*bytes.as_ptr().add(pos).cast()
}
```

It's a very brief function since rkyv is zero-copy.

**Comment by tv42** [comment]
I believe rustc 1.72 in debug mode now validates pointer alignment, and the `archived_root` workaround above also panics.

```
thread 'main' panicked at 'misaligned pointer dereference: address must be a multiple of 0x4 but is 0x55555bc7c63b', crates/foo/src/rkyv_kludge.rs:24:5
```

I fear I'm going to be porting my code away from rkyv next, as RocksDB just doesn't guarantee alignment of its values :-(

**Comment by Chaoses-Ib** [comment]
You can use `transmute` to workaround that:
```rust
#[inline]
pub unsafe fn archived_value<T: Archive + ?Sized>(bytes: &[u8], pos: usize) -> &T::Archived {
    // #[cfg(debug_assertions)]
    // check_alignment::<T::Archived>(bytes.as_ptr());

    let ptr: *const T::Archived = bytes.as_ptr().add(pos).cast();

    // Deferencing an unaligned pointer may panic in debug.
    // We use `transmute` to bypass the check.
    std::mem::transmute(ptr)
}
```
At least in our product, rkyv works fine with RocksDB under x86-64.

**Comment by tv42** [comment]
Hello fellow lurkers. Rkyv 0.8 now has working support for unaligned access!
