### ISSUE TITLE
rkyv: Doc-test failure with rkyv 0.7.27

### ISSUE THREAD

**Issue by remilauzier** [rkyv/rkyv#235]
https://kojipkgs.fedoraproject.org//work/tasks/5232/80165232/build.log

failures:
---- src/lib.rs - Archive (line 240) stdout ----
error[E0425]: cannot find function `check_archived_root` in crate `rkyv`
   --> src/lib.rs:274:22
    |
37  | let archived = rkyv::check_archived_root::<Test>(&bytes[..]).unwrap();
    |                      ^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `archived_root`
    |
   ::: /builddir/build/BUILD/rkyv-0.7.27/src/util/mod.rs:142:1
    |
142 | pub unsafe fn archived_root<T: Archive + ?Sized>(bytes: &[u8]) -> &T::Archived {
    | ------------------------------------------------------------------------------ similarly named function `archived_root` defined here
error: aborting due to previous error

**Comment by djkoloski** [comment]
Should be fixed by a85bce897f410a810666e0abd24ca193db379a09 and released in 0.7.28.
