### ISSUE TITLE
`SharedSerializeMapError` does not implement `Send`/`Sync`, making it difficult to use

### ISSUE THREAD

**Issue by nagisa** [rkyv/rkyv#242]
In general `Error`s should strive to implement `Send`/`Sync` when possible so that passing them across threads down to e.g. main thread is reasonably straightforward.

Usually the errors fail to implement these traits when they have as a payload some type which doesn't need to be there all that badly. I'm not sure if that's the case with [`SharedSerializeMapError`](https://docs.rs/rkyv/latest/rkyv/ser/serializers/enum.SharedSerializeMapError.html), but it contains a pointer which makes it `!Send`/`!Sync`.

Are users inspecting this error expected to do something pointery with the contained pointer, or is it there entirely for ability to inspect the address etc? If its the latter, maybe it would make sense to replace it with an usize?

**Comment by djkoloski** [comment]
This is an oversight, the provided pointer is intended to be used purely for debugging purposes. Changing it to a `usize` is technically an API change, so I think that manually implementing `Send` and `Sync` for `SharedSerializeMapError` is the best path forward. Switching to a `usize` and removing the manual implementations would be good cleanup for the next breaking release.

**Comment by djkoloski** [comment]
Fixed by 1601793a9cb34088ca03299eb0281e647f072e78. This will be released in rkyv 0.7.30 which should be in the next few hours if everything goes smoothly.

**Comment by nagisa** [comment]
Hm, `AllocScratchError` seems to be sharing mostly the same issue, though I'm again not entirely sure if the pointers therein are expected to be used as pointers by the users or not.

**Comment by djkoloski** [comment]
Same thing, all of those error types are meant to be purely for debugging purposes. I would be very shocked if people wanted to try to manually fix up a byte buffer. I’ll get that one sorted too.

**Comment by djkoloski** [comment]
This should be cleaned up by 317599f2e9cbe37ef219b8b44a96bfbc804fb620. The only remaining exception is `SharedDeserializeMap`, which can't be `Send`/`Sync` per #174. Not sure if there's actually a way to fix this, but if you have any ideas you're welcome to chime in on that issue.

I'll get these changes tested and shipped for 0.7.31, which should (hopefully) be sometime later today.
