### ISSUE TITLE
Implement `PartialEq<Duration>` for `ArchivedDuration`

### ISSUE THREAD

**Issue by djkoloski** [rkyv/rkyv#246]
This brings `ArchivedDuration` closer in line with other standard library types, which tend to implement comparison traits when possible.

**Comment by ok-nick** [comment]
`Eq` as well

**Comment by kastolars** [comment]
First time contributor here, I'm opening a draft PR but might need some guidance.

**Comment by djkoloski** [comment]
Fixed by 2066b4192dd545dd12cbc2595bd80714150b935e
