### ISSUE TITLE
`VecDeque` support

### ISSUE THREAD

**Issue by djkoloski** [rkyv/rkyv#250]
Right now, there's not an easy way to archive `VecDeques`. When archived, they're functionally the same as `Vec` so we should be able to piggyback off the implementations for `Vec`.

- [ ] `Archive` impl should archive as `ArchivedVec` and use a `VecResolver` as its resolver.
- [ ] `Serialize` impl should serialize using [`ArchivedVec::serialize_from_slice`](https://docs.rs/rkyv/latest/rkyv/vec/struct.ArchivedVec.html#method.serialize_from_slice). The resolver should just be a `VecResolver`.
- [ ] `Deserialize` impl should deserialize back to a `VecDeque`.
- [ ] `PartialEq` and `PartialOrd` should be implemented similarly to `Vec`.

The [`Vec` implementation](https://github.com/rkyv/rkyv/blob/master/rkyv/src/impls/alloc/vec.rs) should be a good place to start.

**Comment by carvalhais** [comment]
I'd like to take this issue.

**Comment by djkoloski** [comment]
It's all yours! Feel free to reach out if you have any questions.

**Comment by djkoloski** [comment]
Cleanup due to retriaging open issues
