### ISSUE TITLE
the trait bound `WriteSerializer<Vec<u8>>: ScratchSpace` is not satisfied (when trying to serialize a `Vec<Uuid>`)

### ISSUE THREAD

**Issue by DarrenTsung** [rkyv/rkyv#253]
Another compiler issue that I found when trying to upgrade `rkyv` to latest. ~~I narrowed it down to trying to serialize a `Vec<Uuid>`.~~ Actually, it happens whenever I try to serialize a `Vec<_>` of an `Archive`-able type into a `WriteSerializer`.

A minimal repro:
```
use rkyv::*;
use uuid::*;

pub fn foo() {
    let mut serializer = rkyv::ser::serializers::WriteSerializer::new(vec![]);

    // I'm able to serialize a Uuid just fine..
    Uuid::new_v4()
        .serialize(&mut serializer)
        .expect("can serialize");

    // But this throws a compile error
    vec![Uuid::new_v4()]
        .serialize(&mut serializer)
        .expect("can serialize");
}
```

Cargo.toml:
```
[dependencies]
rkyv = {version = "0.7.33", features = ["uuid"]}
uuid = {version = "0.8", features = ["v4"]}
```

Hmm.. after some investigation, when I switch the serializer to an `AllocSerializer` as per the main example in the README, it compiles without issue. 

For context: the reason I am trying to use a `WriteSerializer` is because I want the end result to be a `Vec<u8>`. When I use `AllocSerializer`, it returns an `AlignedVec` which I can only convert to a `Vec<u8>` with [`into_vec()`](https://docs.rs/rkyv/latest/rkyv/util/struct.AlignedVec.html#method.into_vec) which states that it re-allocates and copies the bytes over. Is using `WriteSerializer<Vec<u8>>` instead the right way to do things?

Thanks for your help in advance 🙏🏻.

**Comment by djkoloski** [comment]
I'll take a look!

**Comment by djkoloski** [comment]
Ah, okay this looks like it's not too bad. There's some really awful terminology here, so apologies for that.

A "serializer" kind of has two separate meanings. One is as the context object for the `Serialize` trait. This "serializer" implements `Serializer` as well as `ScratchSpace` and all the other traits you might need. The other "serializer" is just the part of `CompositeSerializer` that implements `Serializer`. `CompositeSerializer` exists to compose your serializer from separate independent components.

I think you may just need to switch your serializer to a `CompositeSerializer<WriteSerializer, AllocScratch, Infallible>`. It's a little more annoying to set up, but it should solve your problem.

**Comment by DarrenTsung** [comment]
Thanks! Switching it to `CompositeSerializer<WriteSerializer, AllocScratch, Infallible>` worked. Makes sense since I wanted something similar to the `AllocSerializer`, but writing to a `Vec<u8>` instead of an `AlignedVec`.
