### ISSUE TITLE
rkyv_derive: not compilable with version 0.7.37 on fedora koji

### ISSUE THREAD

**Issue by remilauzier** [rkyv/rkyv#261]
error[E0599]: no variant or associated item named `__TestExhaustive` found for enum `syn::Type` in the current scope
   --> src/serde/receiver.rs:154:19
    |
154 |             Type::__TestExhaustive(_) => unimplemented!(),
    |                   ^^^^^^^^^^^^^^^^ variant or associated item not found in `syn::Type`
For more information about this error, try `rustc --explain E0599`.
error: could not compile `rkyv_derive` due to previous error

https://kojipkgs.fedoraproject.org//work/tasks/8538/85368538/build.log

**Comment by djkoloski** [comment]
Should be fixed by 12eea30

**Comment by djkoloski** [comment]
Closing, feel free to reopen if that did not fix the issue.
