### ISSUE TITLE
Question: recommended pattern for enum with unsupported types?

### ISSUE THREAD

**Issue by kwonoj** [rkyv/rkyv#262]
I'm tyring to serialize / deserialze a struct, which contains inner properties includes non-supported types: 

```
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)]
struct SomeStruct {
 pub path: PathType
 ...values
}

#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)]
enum PathType {
  Virtual(String),
  Url(Url),
  Real(PathBuf)
}
```

Notably, `Url` and `PathBuf` raises error doesn't satisfy trait bounds. 

For this usecase it doesn't need strict preservation but approximate serialization string would works for me, and thought could use `AsString` (or `ToString?`), but this also doesn't seem to work:

```
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)]
enum PathType {
  Virtual(String),
 #[with(AsString)]
  Url(Url),
 #[with(AsString)]
  Real(PathBuf)
}
```

Is there a way to allow this in a trivial way?

**Comment by djkoloski** [comment]
This should work if you move the `#[with]` inside the parentheses:

```rust
Real(#[with(AsString)] PathBuf)
```

**Comment by djkoloski** [comment]
It looks like the `Url` type doesn't currently have crate support. Which crate are you using it from?

External types can be serialized with wrapper types (`#[with]`), but you may have to write your own `ArchiveWith` implementations. There are some docs [here](https://docs.rs/rkyv/latest/rkyv/with/trait.ArchiveWith.html#example). Feel free to drop into the discord too if you want some additional guidance. 🙂

**Comment by kwonoj** [comment]
> This should work if you move the #[with] inside the parentheses:

🤦 Oh yes, that was my dumb mistakes.

> It looks like the Url type doesn't currently have crate support. Which crate are you using it from?

Yes, it looks like so. This (https://crates.io/crates/url) is the one I'm using. 

I guess I need to try to write `ArchiveWith` to see if it is trivially to do, thanks for the pointer.
