### ISSUE TITLE
Upgrade from 0.6 to 0.7 and archive(copy)

### ISSUE THREAD

**Issue by d00z3l** [rkyv/rkyv#271]
Hi,

I am in the process of upgrading from 0.6 to 0.7 and I am having an issue with `archive(copy)` . It seems that the copy feature is now behind a feature flag and requires nightly? Not sure if that is the case or it is a different feature?

My same code is below:

```rust
#[derive(Debug, Copy, Clone, PartialEq, rkyv::Archive, rkyv::Serialize)]
#[archive(copy)]
pub struct Value {
    id: u32,
    value: f64,
}

#[derive(Debug,  rkyv::Archive,  rkyv::Serialize)]
struct ValueIndex {
    items: Vec<Value>
}

```

**Comment by djkoloski** [comment]
Yes, that is correct. The idea of making specific values copy-optimized has been replaced with instructing the containers to copy-optimize their serialization. In this case, you can do:

```rust
#[derive(Debug, Copy, Clone, PartialEq, rkyv::Archive, rkyv::Serialize)]
pub struct Value {
    id: u32,
    value: f64,
}

#[derive(Debug,  rkyv::Archive,  rkyv::Serialize)]
struct ValueIndex {
    #[with(rkyv::with::CopyOptimize)]
    items: Vec<Value>
}
```

See the [`CopyOptimize docs`](https://docs.rs/rkyv/0.7.38/rkyv/with/struct.CopyOptimize.html) for more information about this specific wrapper. More wrappers are available in the overall [`with` module](https://docs.rs/rkyv/0.7.38/rkyv/with/index.html) as well, including the `Raw` wrapper which can skip validation.

The copy features that you mentioned (`copy` and `copy_unsafe`) are nightly alternatives that can automatically perform copy optimization for you as long as your types are copy optimizable. If you use these features, you don't have to annotate your `Vec`s with the `#[with]` attribute above; all `Vec`s will automatically use copy optimization if it's supported by the element type. You must use `#[archive(copy_safe)]` if you use the `copy` feature without `copy_unsafe`, docs [here](https://docs.rs/rkyv/0.7.38/rkyv/derive.Archive.html#attributes).

**Comment by d00z3l** [comment]
Thanks @djkoloski,

I am wanting to use `Value` directly rather than the generated `ArchivedValue`, I assume that requires `copy` or `copy_unsafe`? If that is the case what has changed to require nightly? I would prefer to stay on stable but not sure if there are flaws in v0.6 when using `#[archive(copy)]`.

**Comment by djkoloski** [comment]
In that case, I think `#[archive(as = "Value")]` is what you want. The `as` argument prevents the generation of the `Archived` version struct and archive using the provided type instead.

**Comment by d00z3l** [comment]
Does that go on the Value struct or on the vec?

**Comment by d00z3l** [comment]
Worked it out:

```rust
#[derive(Debug, Copy, Clone, PartialEq, rkyv::Archive, rkyv::Serialize)]
#[archive(as = "Value")]
pub struct Value {
    id: u32,
    value: f64,
}

#[derive(Debug,  rkyv::Archive,  rkyv::Serialize)]
struct ValueIndex {
    items: Vec<Value>
}

```

**Comment by djkoloski** [comment]
Yep, you'll still need to use the `with` attribute for copy optimization.

**Comment by d00z3l** [comment]
Thanks, with copy optimisation it mentions `and contain no padding bytes`. Is padding referring to alignment? In this case Value is 12 bytes so will align to 16. Not sure if this is safe.

**Comment by djkoloski** [comment]
Padding is referring to any part of the total struct size that's not taken up by a field. If you have padding in your type, you can "remove" it by assigning it to a field like:

```rust
#[repr(C)]
pub struct Value {
    value: f64,
    id: u32,
    _padding: [u8; 4],
}
```

Struct padding can always be moved to the end of the struct by sorting its fields by alignment (high to low). Then you can add a trailing `_padding` field to take up that remaining space. You can check whether your struct contains padding by comparing the sum of the sizes of the fields to the size of the overall struct:

```rust
const_assert_eq!(size_of::<f64>() + size_of::<u32>() + size_of::<[u8; 4]>(), size_of::<Value>());
```

**Comment by d00z3l** [comment]
Thanks
