### ISSUE TITLE
Serialization issues between x86_64 and i386

### ISSUE THREAD

**Issue by sphw** [rkyv/rkyv#273]
My colleague and I have discovered an issue with serialization and deserialization between x86_64 and i386 platforms. As far as I can tell this issue only appears on x86 processors, as I tested on AArch64 and ThumbV8M without issue.

The issue appears with the following structs:

```rust
#[derive(Archive, Serialize, Deserialize, Clone, Debug)]
#[archive_attr(derive(bytecheck::CheckBytes))]
struct Test {
    a: u64,
    e: TestE,
}

#[derive(Archive, Serialize, Deserialize, Clone, Debug)]
#[archive_attr(derive(bytecheck::CheckBytes))]
enum TestE {
    Foo { b: [u8; 4], a: [u8; 4] },
    Bar { a: [u8; 4], b: [u8; 4] },
}
``` 

When serialized on i686 the hex output is `ffffffffffffffff000f0e0d0c01020304000000`.

When serialized on x86_64 the hex output is `ffffffffffffffff000f0e0d0c0102030400000000000000`.

When deserializing the i686 output on x86_64 you get the following error:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CheckBytesError(ContextError(ArchiveError(OutOfBounds { base: 0x55a349ea9b70, offset: -4, range: 0x55a349ea9b70..0x55a349ea9b84 })))', src/main.rs:13:42` 

I have posted test code here: https://github.com/sphw/rkyv-issue/blob/master/src/main.rs

You can test the issue on an x86_64 Linux machine with the following:

```
➜  rkyv-issue git:(master) cargo run --target i686-unknown-linux-gnu
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/i686-unknown-linux-gnu/debug/rkyv-test`
HEX BYTES = ffffffffffffffff000f0e0d0c01020304000000
Test { a: 18446744073709551615, e: Foo { b: [15, 14, 13, 12], a: [1, 2, 3, 4] } }
➜  rkyv-issue git:(master) cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/rkyv-test`
HEX BYTES = ffffffffffffffff000f0e0d0c0102030400000000000000
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CheckBytesError(ContextError(ArchiveError(OutOfBounds { base: 0x55a349ea9b70, offset: -4, range: 0x55a349ea9b70..0x55a349ea9b84 })))', src/main.rs:13:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

All credit to @sadroeck for discovering this.

**Comment by djkoloski** [comment]
Looks like there are a couple possible solutions here:
- Serialize 64-bit integers as a custom type (possibly only on 32-bit platforms).
- Disable 64-bit integers on 32-bit platforms altogether.
- Remove builtin support for 64-bit integers on 32-bit platforms and provide a wrapper type (e.g. `#[with(Align)]`)
This is also some tech debt that I'm planning to address with the next major release. For now I think that the last solution is probably the most reasonable.

**Comment by djkoloski** [comment]
This has been fixed by always requiring use of rend's types for primitives, and rend always wrapping primitives in an explicitly-aligned wrapper type.
