### ISSUE TITLE
Document how to avoid leaking private types using `#[omit_bounds]`

### ISSUE THREAD

**Issue by droundy** [rkyv/rkyv#275]
I have a type that looks like:
```
#[derive(Archive)]
pub struct IdentifierId {
    inner: IdentifierIdInner
}
```
which is giving me an error because `IdentifierIdInner` is a private type (which is the whole point).  Is there a solution to this? Presumably I could just manually implement `Archive`, but it would be much nicer to derive it.

Here is the error message I get:
```
error[E0446]: private type `IdentifierIdInner` in public interface
   --> workspace/nemo_core/src/hashtypes.rs:95:72
    |
95  | #[derive(Copy, Clone, Hash, PartialEq, Eq, PartialOrd, Ord, Serialize, Archive)]
    |                                                                        ^^^^^^^ can't leak private type
...
118 | enum IdentifierIdInner {
    | ---------------------- `IdentifierIdInner` declared as private
    |
    = note: this error originates in the derive macro `Archive` (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by djkoloski** [comment]
Could you provide a minimal repro? This sounds like an issue with generated structure/field visibility, but I'll need to expand the macro to be sure.

**Comment by droundy** [comment]
```
use rkyv::Archive;

#[derive(Archive)]
struct Inner(u32);

#[derive(Archive)]
pub struct Outer(Inner);
```

**Comment by droundy** [comment]
In doing this, I discovered that this is a warning (I had a stricter configuration), not an error, but the warning claims it will be a hard error in the future.
```
warning: private type `Inner` in public interface (error E0446)
 --> src/lib.rs:6:10
  |
6 | #[derive(Archive)]
  |          ^^^^^^^
  |
  = note: `#[warn(private_in_public)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #34537 <https://github.com/rust-lang/rust/issues/34537>
  = note: this warning originates in the derive macro `Archive` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `test-rkyv` (lib) generated 1 warning
```

**Comment by djkoloski** [comment]
It looks like the issue in this case is because the archived type is being generated like this:
```rust
///An archived [`Outer`]
pub struct ArchivedOuter(
    ///The archived counterpart of [`Outer::0`]
    ::rkyv::Archived<Inner>,
)
where
    Inner: ::rkyv::Archive;
```
and that `where` clause is exposing `Inner` in a public interface. I'm not sure that this clause can be removed in general, but I'll poke around and see how it interacts with generics.

**Comment by djkoloski** [comment]
Quick follow-up on this: it was observed that in many cases `#[omit_bounds]` can be used to suppress the generation of those problematic bounds. In some cases, you may need to also add [explicit bounds](https://docs.rs/rkyv/latest/rkyv/derive.Archive.html#attributes) using `#[archive(bound(...))]`.

**Comment by djkoloski** [comment]
Added a new section for this in 6c2e1e762e70ee07bd6b25c8f31ff0d36dcda283
