### ISSUE TITLE
Derive macro option for modifying visibility of generated types

### ISSUE THREAD

**Issue by droundy** [rkyv/rkyv#276]
This is because I'm creating an intermediate type.  So my user creates type `Original`, from which I create an `Intermediate`, which derives `Archive` and produces an archived type that I want to expose publicly.  Is this possible?

**Comment by djkoloski** [comment]
Is this still an issue? Rust has made some changes to how it handles private types in public re-exports and interfaces. If it is still an issue, can you provide a repro?
