### ISSUE TITLE
ICE while deriving `CheckBytes` on a struct containing a `Cow` with `AsOwned` attribute

### ISSUE THREAD

**Issue by metent** [rkyv/rkyv#286]
MCVE:
```rust
#[derive(rkyv::Serialize, rkyv::Archive)]
#[archive_attr(derive(bytecheck::CheckBytes))]
struct IceStruct<'a> {
	#[with(rkyv::with::AsOwned)]
	ice_str: Cow<'a, str>,
}
```

ICE:
```
error: internal compiler error: compiler/rustc_middle/src/ty/normalize_erasing_regions.rs:199:90: Failed to normalize fn(std::result::Result<&<rkyv::with::With<std::borrow::Cow<str>, rkyv::with::AsOwned> as rkyv::Archive>::Archived, <<rkyv::with::With<std::borrow::Cow<str>, rkyv::with::AsOwned> as rkyv::Archive>::Archived as bytecheck::CheckBytes<__C>>::Error>
```

**Comment by djkoloski** [comment]
Thanks for the minimal repro. ICEs should be reported upstream to rust-lang/rust, done there's not much we can do about it in rkyv. Would you mind filling an issue there instead?

**Comment by metent** [comment]
It appears there are already multiple similar bug reports upstream (https://github.com/rust-lang/rust/issues/94651 and https://github.com/rust-lang/rust/issues/97661). Sorry for the noise. Feel free to close this issue or you can keep this open until it is fixed upstream.

**Comment by djkoloski** [comment]
No worries! I appreciate the care you took to investigate this. 🙂 Closing this in favor of the linked issues.
