### ISSUE TITLE
Re-export all public dependencies

### ISSUE THREAD

**Issue by eggyal** [rkyv/rkyv#290]
Currently, implementors of (for example) `ArchiveUnsized` must add *the correct version* of `ptr_meta` to their own dependencies.  If `rkyv` were instead to re-export `ptr_meta`, or at very least the relevant parts of it, users could simply use those re-exports instead.

**Comment by djkoloski** [comment]
Are there any guidelines on when dependencies should be re-exported? Doing so may make it easier in some cases, but I'm worried about causing dependency resolution issues.

**Comment by eggyal** [comment]
[Effective Rust, Item 25](https://lurklurk.org/effective-rust/re-export.html) recommends at very least re-exporting any types that appear in your public API.

I personally go a step further and reexport the entire crate in which those types appear, as downstream users may require other parts of the crate to generate or consume those types required by my API.

**Comment by eggyal** [comment]
You may also find [this discussion](https://github.com/rust-lang/api-guidelines/discussions/176) in the official "API guidelines" repo relevant/useful.
