### ISSUE TITLE
Overflow in `Duration::new` when parsing malformed duration

### ISSUE THREAD

**Issue by 5225225** [rkyv/rkyv#297]
```rust
fn main() {
    rkyv::from_bytes::<std::time::Duration>(&[0xff; 16]);
}
```

This is using `from_bytes`, so this should be checked, but this still panics. Duration::new has an overflow condition that needs to be checked here.

**Comment by djkoloski** [comment]
Thanks for finding this issue. Fixed by ac62695d4e2fce0b9b5aadebd22063ee68151215
