### ISSUE TITLE
Docs for how to derive CheckBytes for a recursive type?

### ISSUE THREAD

**Issue by 5225225** [rkyv/rkyv#299]
Not quite a bug report but... I cannot figure out how to do it. And no example actually does it.

I'm trying

```rust
#[derive(rkyv::Archive, rkyv::Deserialize)]
#[archive_attr(derive(bytecheck::CheckBytes))]
#[archive_attr(bound(""))]
enum AllValues {
    Vec(#[omit_bounds] #[archive_attr(omit_bounds)] Vec<AllValues>),
}
```
(with a lot more real fields for the actual enum, i just cut it down for simplicity)

but the `archive_attr(bound)` there is not seen as a valid attribute. So I'm stuck here.

**Comment by djkoloski** [comment]
The issue in this case is the difference between the `#[archive(...)]` and `#[archive_attr(...)]` attributes. The difference between them is provided in more detail in the [documentation for the derive macro](https://docs.rs/rkyv/latest/rkyv/derive.Archive.html#attributes). The [JSON example](https://github.com/rkyv/rkyv/blob/master/examples/json/src/main.rs) also provides an example of using the `bound` argument for self-referential types. Would explicitly linking to those examples from the README make them discoverable enough?

**Comment by 5225225** [comment]
Yeah, the JSON example being written using CheckBytes would be good. That example of deriving CheckBytes isn't being put on an `Archived` type, so it doesn't immediately translate over to using `#[archive_attr(derive(CheckBytes))]`.

**Comment by 5225225** [comment]
Okay, I looked at the docs again, and realised you needed to do `archive_attr(check_bytes(bound = ...))`

So the final result is

```rust
#[derive(rkyv::Archive, rkyv::Deserialize)]
#[archive_attr(derive(bytecheck::CheckBytes))]
#[archive_attr(check_bytes(bound = "__C: rkyv::validation::ArchiveContext, <__C as rkyv::Fallible>::Error: std::error::Error"))]
enum AllValues {
    Vec(#[omit_bounds] #[archive_attr(omit_bounds)] Vec<AllValues>),
}
```

That's highly unintuitive. But hey, I figured it out!

**Comment by djkoloski** [comment]
The `json` example has been updated with validation support as of 874f684d20fd4539858777db852d91b6c68ee286
