### ISSUE TITLE
with::Lock can corrupt data

### ISSUE THREAD

**Issue by sporksmith** [rkyv/rkyv#309]
While the [with::Lock documentation](https://docs.rs/rkyv/0.7.1/rkyv/with/struct.Lock.html) notes that a panic can result if another thread poisons the lock, there's actually a subtler issue that can result in data corruption.

If another thread takes the lock and mutates the data in between the calls to `serialize` and `archive`, `archive` can misbehave in unpredictable ways.

Here's an example with a `Mutex<Vec<i32>>`. If data is appended to the vector in between the two calls, then the call to `archive` can end up mistakenly assuming the new members were already serialized, and end up pointing to garbage data instead.

```
use rkyv::{
    ser::{serializers::{AllocSerializer, CompositeSerializerError, AllocScratchError, SharedSerializeMapError}, Serializer, ScratchSpace},
    Serialize, Fallible, with::LockError,
};
use rkyv::{with::Lock, Archive};
use std::{sync::Arc, collections::HashMap};
use std::sync::Mutex;

// We need to define a custom serializer to use with::Lock
struct MySerializer {
    inner: AllocSerializer<0>,
}

impl Serializer for MySerializer {
    fn pos(&self) -> usize {
        self.inner.pos()
    }

    fn write(&mut self, bytes: &[u8]) -> Result<(), Self::Error> {
        self.inner.write(bytes).map_err(|e|  e.into())
    }
}

impl ScratchSpace for MySerializer {
    unsafe fn push_scratch(&mut self, layout: std::alloc::Layout) -> Result<std::ptr::NonNull<[u8]>, Self::Error> {
        self.inner.push_scratch(layout).map_err(|e| e.into())
    }

    unsafe fn pop_scratch(&mut self, ptr: std::ptr::NonNull<u8>, layout: std::alloc::Layout) -> Result<(), Self::Error> {
        self.inner.pop_scratch(ptr, layout).map_err(|e| e.into())
    }
}

#[derive(Debug)]
struct MySerializerError {}

impl Fallible for MySerializer {
    type Error = MySerializerError;
}

impl From<LockError> for MySerializerError {
    fn from(_: LockError) -> Self {
        Self {}
    }
}

impl From<CompositeSerializerError<std::convert::Infallible, AllocScratchError, SharedSerializeMapError>> for MySerializerError {
    fn from(_: CompositeSerializerError<std::convert::Infallible, AllocScratchError, SharedSerializeMapError>) -> Self {
        Self {}
    }
}

#[derive(Archive, Serialize)]
struct MyStruct {
    #[with(Lock)]
    v: Mutex<Vec<i32>>,
}

fn main() {
    // debug-string of the collection -> # of times observed
    let mut results = HashMap::<String, u32>::new();

    // run many times, since we're trying to reproduce a race condition
    for _ in 0..1000000 {
        let ms = Arc::new(MyStruct {
            v: std::sync::Mutex::new(Vec::new()),
        });

        let ms2 = ms.clone();
        let serializer_thread = std::thread::spawn(move || {
            let mut serializer = MySerializer { inner: AllocSerializer::<0>::default() };
            serializer.serialize_value(&*ms2).unwrap();
            serializer.inner.into_serializer().into_inner()
        });

        ms.v.lock().unwrap().push(42);
        ms.v.lock().unwrap().push(43);
        ms.v.lock().unwrap().push(44);
        ms.v.lock().unwrap().push(45);
        ms.v.lock().unwrap().push(46);
        ms.v.lock().unwrap().push(47);
        ms.v.lock().unwrap().push(48);
        ms.v.lock().unwrap().push(49);

        let buf = serializer_thread.join().unwrap();

        let archived = unsafe { rkyv::archived_root::<MyStruct>(&buf[..]) };

        *(results.entry(format!("{:?}", archived.v)).or_default()) += 1;
    }
    println!("{:?}", results);
}
```

Here's a sample output I get:

```
{"Immutable([42, 43, 44, 45, 46, -20, 8, 49])": 2, "Immutable([])": 25, "Immutable([42, 43, 44, 45, 46])": 1, "Immutable([42, 43])": 1, "Immutable([0])": 1, "Immutable([42, -4])": 2, "Immutable([42, 43, 44, 45])": 1, "Immutable([42, 43, 44, 45, 46, 47, 48, 49])": 999960, "Immutable([42, 43, 44, 45, 46, 47, 48])": 3, "Immutable([42, 43, 44, 45, 46, 47])": 3, "Immutable([0, 2])": 1}
```

While it got a reasonable output in most of the trials, in ones that got by the race condition we get a vector with garbage data that was never inserted into it.

**Comment by djkoloski** [comment]
Thanks for the bug report. I think the only way we could fix this kind of locking behavior would be to hold the lock in a read-only state between `serialize` and `resolve`. In the meantime, we should document this behavior. In the future, perhaps we should introduce an `Unsafe<T>` wrapper and allow wrappers to be unsafe. So instead of adding `#[with(Lock)]`, we'd add something like `#[with(Unsafe<Lock>)]`. I think that removing the ability to serialize mutexes at all would be a bummer, but it may end up being necessary for safety.

**Comment by sporksmith** [comment]
Yeah, seems like there's no quick answer, other than documenting or removing it in the meantime. 

I wonder if the `SerializeWith` and `Serialize` traits could be modified to specify that the serializer must outlive the object. In that case `SerializeWith<Mutex<F>, S> for Lock` could store a lock in its serializer, thus preventing its data from being mutated until the serializer is dropped. I'm not of the exact syntax of this or whether it's possible to express at all, but it seems like it ought to be.

This would be a breaking change, since the callers would henceforth be forced to ensure that serializers don't outlive the object it came from, but I don't imagine that would ultimately be a huge burden.

**Comment by djkoloski** [comment]
This behavior is now documented in 11090aaa98e4be6f371a03c928ff331d2fd03fa8. I'm going to leave this issue open so it can be addressed in a substantial way in the future.

**Comment by djkoloski** [comment]
After running into this kind of situation with other types (e.g. iterators), I have decided that `resolve` cannot be unsafe and neither can `Archive`. As a result, rkyv's policy going forward will be that writing data that wouldn't pass validation is **not** a memory safety violation. The serialization impls in rkyv will make the best possible effort to never do that, but making it a provable safety requirement is not tenable.
