### ISSUE TITLE
Add support for tokio's `bytes::Bytes` types.

### ISSUE THREAD

**Issue by ChillFish8** [rkyv/rkyv#314]
Tokio's `Bytes` structures are probably the second most popular way of manipulating and working with a lot of binary data outside of a `Vec<u8>` itself, it would be really nice to have support for this with Rkyv!

**Comment by dignifiedquire** [comment]
Any thoughts on when this might happen? In an async context this is the easiest way to achieve zero copy for IO, and I would love to combine this with rkyv.

**Comment by djkoloski** [comment]
Adding support wouldn't be a semver-breaking change, so we can add support at any time. If anyone wants to take a crack at it, the impl for `Bytes` should be very similar to the impl for `tinyvec`'s types.
