### ISSUE TITLE
"variants never constructed" lint regression in Rust 1.64.0

### ISSUE THREAD

**Issue by bunnie** [rkyv/rkyv#318]
I'm using a fairly old version of rkyv (0.4.3) and wondering if this lint warning is also appearing for users in later versions of rkyv:

```

warning: variants `Sha512Result`, `Sha512Trunc256Result`, `SuspendError`, `Uninitialized` and `IdMismatch` are never constructed
 --> services\engine-sha512\src\api.rs:5:5
  |
3 | #[derive(Debug, rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)]
  |                 ------------- variants in this enum
4 | pub enum Sha2Result {
5 |     Sha512Result([u8; 64]),
  |     ^^^^^^^^^^^^
6 |     Sha512Trunc256Result([u8; 32]),
  |     ^^^^^^^^^^^^^^^^^^^^
7 |     SuspendError,
  |     ^^^^^^^^^^^^
8 |     Uninitialized,
  |     ^^^^^^^^^^^^^
9 |     IdMismatch,
  |     ^^^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default
  ```

This just started appearing in Rust 1.64.0; in Rust 1.63.0 and older, such warnings were not emitted.

We try to keep our builds 100% free of warnings, so we can actually see warnings that matter when the builds happen. Unfortunately, we use a lot of rkyv so with this regression our build logs are overwhelmed with Rust complaining about Archive-derived enums not being used.

I tried to actually construct the derived enums with some code like this:

```rust
    pub fn use_rust_1_64_enums(&self, val: u32) -> ArchivedSha2Result {
        match val {
            0 => ArchivedSha2Result::Sha512Result([0; 64]),
            1 => ArchivedSha2Result::Sha512Trunc256Result([0; 32]),
            2 => ArchivedSha2Result::IdMismatch,
            3 => ArchivedSha2Result::SuspendError,
            _ => ArchivedSha2Result::Uninitialized,
        }
    }
```

But even if I call this code and pass the result on to something else, Rust is insisting that we never construct that enum type (tried creating both the ArchivedSha2Result and the Sha2ResultResolver and casting the results to something the compiler shouldn't disregard). I'm guessing maybe the derive creates some extra enum types that I'm not aware of or perhaps it does something exciting with the discriminants that cause the rust linter to think variants are not being used.

Furthermore, if I add `#[allow(dead_code)]` to the enum definition, it still throws the warning; adding `#[allow(dead_code)]` to every element has the same result, more warnings.

The only way I've been able to silence this is to use the "big hammer" of `#![allow(dead_code)]` to the entire file.

So, the current work-around I have is to move all rkyv-derive types to its own file, and then drop the file-wide silencer on top.

This is an acceptable work-around; but now I am left with lingering curiosity!

If this is also happening in the latest rkyv, maybe this is a compiler regression? If it's not happening, something else subtle going on that I'm not understanding in order to construct the derived variants so I can make the warning go away...?

**Comment by bunnie** [comment]
Ah, one other important detail to note -- the warnings only happen in `rkyv` enums that take values, that is enums that have variants that take some other type as an argument.

Simple enums that are just lists of keywords with no values work just fine.

**Comment by bunnie** [comment]
thanks! For now the work-around I have of moving rkyv-types to their own file is working so far.

If it turns out to be a distraction to backport to 0.4.*, we plan to forward-port our bindings to your 0.8 release once that's ready!

**Comment by djkoloski** [comment]
Marking this as obsolete, since I can't afford to maintain more than a single point-release back for rkyv.
