### ISSUE TITLE
Cannot archive as Self with PhantomData

### ISSUE THREAD

**Issue by MaxOhn** [rkyv/rkyv#324]
Looks like types containing `PhantomData` currently can't be archived as Self.
```rs
#[derive(rkyv::Archive)]
#[archive(as = "Self")]
struct Test<T> {
    phantom: std::marker::PhantomData<T>,
}
```
The above code currently (`rkyv 0.7.39`) results in
```
error[E0308]: mismatched types
   --> src/main.rs:7:10
    |
7   | #[derive(Archive)]
    |          ^^^^^^^
    |          |
    |          expected associated type, found struct `PhantomData`
    |          arguments to this function are incorrect
    |
    = note: expected raw pointer `*mut <PhantomData<T> as Archive>::Archived`
               found raw pointer `*mut PhantomData<T>`
    = help: consider constraining the associated type `<PhantomData<T> as Archive>::Archived` to `PhantomData<T>` or calling a method that returns `<PhantomData<T> as Archive>::Archived`
    = note: for more information, visit https://doc.rust-lang.org/book/ch19-03-advanced-traits.html
```
Since `PhantomData` archives [into itself](https://github.com/rkyv/rkyv/blob/9f70aa34b5bde00fdf314d2a04b6d5c0fef5b335/rkyv/src/impls/core/primitive.rs#L187) I expected this to work.

Probably caused by some complications in the `Archive` derive macro?

**Comment by djkoloski** [comment]
Can you try `as = Test<T>` instead of `Self`?

**Comment by MaxOhn** [comment]
> Can you try `as = Test<T>` instead of `Self`?

Same result unfortunately

**Comment by djkoloski** [comment]
Oh sorry, I mean `as = Self<T::Archived>`. Is that what you want?

**Comment by MaxOhn** [comment]
```rs
#[derive(Archive)]
#[archive(as = "Test<<T as Archive>::Archived>")]
struct Test<T> {
    phantom: PhantomData<T>,
}
```
This complains that `T` does not implement `Archive`

```rs
#[derive(Archive)]
#[archive(as = "Test<<T as Archive>::Archived>")]
struct Test<T: Archive> {
    phantom: PhantomData<T>,
}
```
This complains that `<T as Archive>::Archived` does not implement `Archive`

```rs
#[derive(Archive)]
#[archive(as = "Test<<T as Archive>::Archived>")]
struct Test<T: Archive<Archived = T>> {
    phantom: PhantomData<T>,
}
```
And this gives the initial error about `*mut PhantomData<T>` again.
Anything I missed?

**Comment by djkoloski** [comment]
I think you should be able to do something with `#[omit_bounds]` in the worst case. I can also take a look a bit later.

**Comment by MaxOhn** [comment]
```rs
#[derive(Archive)]
#[archive(as = "Test<<T as Archive>::Archived>")]
struct Test<T: Archive<Archived = T>> {
    #[omit_bounds]
    phantom: PhantomData<T>,
}
```
This seems to be the only one that rust finally accepts. Requiring the bounds on `T` is a little sad though.

If I understand correctly, if the generic `T` only appears in `PhantomData`s down the line the bounds shouldn't technically be necessary but I imagine this is a very tricky edge case to support.

**Comment by djkoloski** [comment]
This seems to work:
```rust
use core::marker::PhantomData;
use rkyv::Archive;

#[derive(Archive)]
#[archive(as = "Self", bound(archive = "PhantomData<T>: Archive<Archived = PhantomData<T>>"))]
struct Test<T> {
    phantom: PhantomData<T>,
}
```

Maybe the compiler just needed some help understanding that `PhantomData` archives to itself? There's only one [blanket impl](https://docs.rs/rkyv/latest/rkyv/trait.Archive.html#impl-Archive-for-PhantomData%3CT%3E) for it.

**Comment by MaxOhn** [comment]
Works great, thanks!
