### ISSUE TITLE
Implement ManuallyDrop

### ISSUE THREAD

**Issue by rrichardson** [rkyv/rkyv#325]
Presently,  Archive and Serialize are not implemented for [ManuallyDrop](https://doc.rust-lang.org/stable/std/mem/struct.ManuallyDrop.html) 

Naively, Serialize for ManuallyDrop<T> should be simple to implement. It'd just invoke T.  
In the derive code, it should just generate an ArchivedT where the ArchivedT is rendered in place of ManuallyDrop<T>. 
The data contained within should be part of the greater buffer, and therefore shouldn't be managed by T.  

Thoughts?

**Comment by djkoloski** [comment]
I think that seems reasonable since `ManuallyDrop` is equivalent to `T` for most purposes (and `Drop` doesn't have an equivalent when archived).

**Comment by djkoloski** [comment]
Fixed by 8bc2a0840eabd0fa5461754fa6aa009882600cd1
