### ISSUE TITLE
`mmap` problem in linux

### ISSUE THREAD

**Issue by llllllvty** [rkyv/rkyv#336]
I used rkyv to serialize a data structure in a file.  But the data  I read from mmap and archived_root is wrong. When I read data into memory and use archived_root to read data, the data is correct. And this problem only on Linux, there's no same problem in windows.
However, this problem only occurs in my program. When I extract the data structure and run some test, there's no problem.
This is the code in the  program:
the data structure
```
#[derive(Debug, Default, Clone, Archive, rkyv::Serialize)]
#[archive_attr(derive(CheckBytes, Debug))]
pub struct UnityProfilerMemoryHeader {
    pub time_stamp: i64,
    pub frame_index: i32,
    pub mono_used: i64,
    pub mono_reserved: i64,
}

#[derive(Debug, Default, Archive, rkyv::Serialize)]
#[archive_attr(derive(CheckBytes, Debug))]
pub struct SingleFrameStackInfo {
    pub profiler_size: i32,
    pub managed_info: HashMap<u64, i32>,
}

#[derive(Debug, Default, Archive, rkyv::Serialize)]
#[archive_attr(derive(CheckBytes, Debug))]
pub struct SingleFrameInfo {
    pub frame_stack_info: HashMap<u64, SingleFrameStackInfo>,
}

#[derive(Debug, Default, Archive, rkyv::Serialize)]
#[archive_attr(derive(CheckBytes, Debug))]
pub struct GCStackInfo {
    pub hash: u64,
    pub stack: Vec<u64>,
}

#[derive(Debug, Default, Archive, rkyv::Serialize)]
#[archive_attr(derive(CheckBytes, Debug))]
pub struct MemoryAnalyze {
    pub start_index: i32,
    pub str_hash: HashMap<u64, String>,
    pub stack_infos: HashMap<u64, GCStackInfo>,
    pub frame_infos: Vec<SingleFrameInfo>,
    pub frame_header: Vec<UnityProfilerMemoryHeader>,
}
```
the serialize and mmap code:
```
pub async fn save_data_to_rkyv(&self, path: &str, name: &str) -> Result<(), Error> {
        let file_path = format!("{path}/{name}.rkyv");
        let mut write_file = tokio::fs::File::create(&file_path)
            .await
            .map_err(UnityMemoryProfilerError::CannotCreateFile)?;
        let bytes =
            rkyv::to_bytes::<MemoryAnalyze, 256>(self).map_err(Error::RkyvSerializeError)?;
        write_file.write_all(&bytes).await?;
        Ok(())
}

let file = tokio::fs::File::open(file_path).await?;
let mmap = lh_profiler_utils::mmap(&file);
let archived = lh_profiler_utils::archived_root::<MemoryAnalyze>(&mmap);
```
the print before serialize and after mmap:
![linux error](https://user-images.githubusercontent.com/46164370/215935684-f9e164a7-1465-43bc-bf6f-5b9fc9109d64.jpg)
but there's no problem in windows:
![windows](https://user-images.githubusercontent.com/46164370/215935727-535ffd84-5bb4-4f73-9f15-9277155b16ec.jpg)

the version of rkyv is 0.7.39 and the version of memmap2 is 0.5.8

**Comment by djkoloski** [comment]
Unfortunately there's not much I can do to help unless I have a reproduction. Could you try minimizing the issue in your project? It may also be worth running MIRI if possible (unlikely) to make sure there's no UB happening.

**Comment by llllllvty** [comment]
> Unfortunately there's not much I can do to help unless I have a reproduction. Could you try minimizing the issue in your project? It may also be worth running MIRI if possible (unlikely) to make sure there's no UB happening.
> 
> _Edit:_ Another good check would be to try removing rkyv from the equation altogether. If you can remove rkyv and the issue still reproduces, then it must be an issue with something else.

**Comment by llllllvty** [comment]
> Unfortunately there's not much I can do to help unless I have a reproduction. Could you try minimizing the issue in your project? It may also be worth running MIRI if possible (unlikely) to make sure there's no UB happening.
> 
> _Edit:_ Another good check would be to try removing rkyv from the equation altogether. If you can remove rkyv and the issue still reproduces, then it must be an issue with something else.

Sorry, I did some other tests. I found that this happened after I upgraded the tokio version. The 1.25.0 version of tokio changes the buff size, I think there might be an alignment issue that causes the bug in linux. It may not be a bug of rkyv.
