### ISSUE TITLE
Different layout between nightly-2023-02-14 and nightly-2023-02-15 causes OOM

### ISSUE THREAD

**Issue by MikaelCall** [rkyv/rkyv#362]
Hi,

We ran into a problem the other day after bumping rust. Trying to read rkyv:ed data failed with OOM, e.g.

```
memory allocation of 420906795024 bytes failed
Aborted (core dumped)
```

I've tracked it down to the update in the title. I've tried rkyv 0.7.39 and 0.7.40.

```sh
$ rustup default nightly-2023-02-14
$ rustc -V
rustc 1.69.0-nightly (065852def 2023-02-13)
$ cargo -V
cargo 1.69.0-nightly (82c3bb79e 2023-02-04)
```

I can use this version to read rkyv:ed data, i.e. data persisted by some version of rust up until nightly-2023-02-14.

However, with the following rust

```sh
$ rustup default nightly-2023-02-15
$ rustc -V
rustc 1.69.0-nightly (0416b1a6f 2023-02-14)
$ cargo -V
cargo 1.69.0-nightly (39c13e67a 2023-02-12)
```

I get OOM in debug and release mode, something like

```sh
...
memory allocation of 420906795024 bytes failed
Aborted (core dumped)
```

Maybe this can be of value? 420906795024 = 0x6200000010.

I've also confirmed that data persisted using nightly-2023-02-15 can be read with nightly-2023-02-15 without problems.

My struct is pretty big and I've not yet tried to construct a small(er) reproducible example. I'd like to discuss possible updates in the compiler that could have caused this and some input on where you'd propose to start.

**Comment by djkoloski** [comment]
Are you validating your data with bytecheck? That may tell you whether your data is in the expected format. Recently, the Rust compiler changed [its layout algorithm](https://github.com/rust-lang/rust/blob/master/RELEASES.md#compatibility-notes-1) for structs, which can affects rkyv's serialized format. rkyv has the `strict` feature to prevent this kind of layout change from impacting your serialized format, but it comes at the cost of wasted space. In the next minor version bump, this feature will also be turned on by default.

**Comment by MikaelCall** [comment]
Thank you. This explains very well what's happened.

I'm thinking that I'll have to write a migration (e.g. by going via some other serialization format) that convert from pre-layout-change to post-layout-change the next time I decide to bump rust.

Whether to use bytecheck, strict or "just handle it" I guess is application specific and I'll probably go with the latter and make sure that this is caught a priori to reduce cost, e.g. by running tests that use the current serialization and makes sure that it can be deserialized as expected using my updated to-be-deployed code.

**Comment by Enter-tainer** [comment]
> In the next minor version bump, this feature will also be turned on by default.

I think the latest version didn't enabled it by default. Also I'd suggest that remove "This is already the case in practice" in feature introduction. This is misleading and not true. There are no other guarantees of data layout made by the default representation.

> strict: Guarantees that types will have the same representations across platforms and compilations. This is already the case in practice, but this feature provides a guarantee along with C type compatibility.

**Comment by Enter-tainer** [comment]
I also wonder if repr C can make solve this problem because u128/i128 seems to have different alignment due to a bug of llvm https://github.com/rust-lang/rust/issues/54341. Therefore if a struct contains u128, it will very likely to have a different layout on arm64/x86 machines even if repr c is enabled.

**Comment by djkoloski** [comment]
To clarify, the next minor bump will be 0.**8**.0, not 0.7.43. Semver versioning makes this terminology unintuitive pre-1.0.

I am unfortunately aware of the issues with alignment of large integer types, it's a long-standing problem. Luckily much of this problem is mitigated by having strict validation for archived types. The correct solution for rkyv is to change the archived types for large integers to a more highly aligned wrapper, such as:

```rust
#[repr(C, align(16))]
struct U128(u128);
```

**Comment by Enter-tainer** [comment]
cool, manually specifing alignment can help with remove the differences on different architectures
