### ISSUE TITLE
archive_le conflicts when being used in a workspace

### ISSUE THREAD

**Issue by cholcombe973** [rkyv/rkyv#366]
I thought about filing a bug against cargo but I think this might be specific to rkyv. I have a top level workspace that imports rkyv like so:
```
[workspace]
rkyv = { version = "0.7.40", features = ["strict", "validation", "copy"] }
```
I also have 2 crates in the workspace that differ in their feature flags. One uses `archive_le` and other doesn't. If I cd into each crate and `cargo check` them individually they work fine. If I try to compile from the top of the workspace one of the crates fails saying that it expected LittleEndian types but couldn't find it. 
Example:
```
    |
71  |     NoUninit, Archive, Serialize, Debug, Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash,
    |               ^^^^^^^
    |               |
    |               expected `*mut LittleEndian<u64>`, found `*mut u64`
    |               arguments to this function are incorrect
    |
    = note: expected raw pointer `*mut LittleEndian<u64>`
               found raw pointer `*mut u64`
```

The two workspace crate imports look like:
`rkyv = { workspace = true, features = ["strict", "validation", "copy"] }`

and the other is `rkyv = { workspace = true, features = ["strict", "archive_le", "validation", "copy", "uuid"] }`

I've tried disabling the top level workspace import and just having each crate import rkyv separately but that doesn't fix it. I suspect this might be because the feature flags in rkyv conflict with one another. 
I've also tried changing the resolver from v1 to v2 but the result is the same.

**Comment by djkoloski** [comment]
Unfortunately I think this is a result of how feature resolving works in cargo. Just to be sure, you're saying that running `cargo check` from inside the crate's directory is fine? Does `cargo build` create a `target` directory there as well? That would explain why the features don't conflict in that case.

**Comment by djkoloski** [comment]
Feature resolver for 0.8 has been updated to 2, and rend's `LittleEndian` struct is gone now. Closing this issue due to staleness.
