### ISSUE TITLE
Lifetimes in generics of TypeName derive macro cause compile errors

### ISSUE THREAD

**Issue by edfraenkel** [rkyv/rkyv#374]
If there are lifetimes in the generic parameters of a struct definition then using the TypeName derive macro causes compile errors.

The following code fails to compile when the two lines marked with _A_ are enabled:

```rust
#[derive(TypeName)]
struct WithLifetime<
//  'a,              // A compile error
//  B,               // B ok
> {
    life: u32,
//  r#is: &'a u128,  // A compile error
//  hard: B,         // B ok
}
```

In fact there are at least two failure modes:
1) Uncommenting the lines marked with _A_ causes:
```
error: proc-macro derive panicked
 --> src\main.rs:4:10
  |
4 | #[derive(TypeName)]
  |          ^^^^^^^^
  |
  = help: message: called `Option::unwrap()` on a `None` value
```

2) Uncommenting all lines _A_ and _B_ causes:
```
error[E0726]: implicit elided lifetime not allowed here
 --> src\main.rs:4:10
  |
4 | #[derive(TypeName)]
  |          ^^^^^^^^ expected lifetime parameter
  |
  = note: this error originates in the derive macro `TypeName` (in Nightly builds, run with -Z macro-backtrace for more info)
help: indicate the anonymous lifetime
  |
4 | #[derive(T'_, ypeName)]
  |           +++
```

The first failure can be explained by line 98 which causes the panic in line 103 because it incorrectly checks that `results` iterates over at least one element.

https://github.com/rkyv/rkyv/blob/1aea469278da6bbed66c4dc20efd589c0b9059b6/rkyv_typename_derive/src/lib.rs#L98-L103

**Comment by djkoloski** [comment]
`rkyv_typename` has been removed since `rkyv_dyn` has been refactored to no longer require it. Closing this issue.
