### ISSUE TITLE
internal compiler error

### ISSUE THREAD

**Issue by ssh352** [rkyv/rkyv#376]
rustc 1.68.2
cargo bench generates internal compiler error. Pls advise. 

<img width="2132" alt="Screenshot 2023-04-03 at 10 21 12 PM" src="https://user-images.githubusercontent.com/41779116/229538045-bfced393-a00f-444d-8403-b8f97d70342e.png">

**Comment by djkoloski** [comment]
There's not much we can do about this in rkyv, we should minimize this and report it upstream at https://github.com/rust-lang/rust. Do you have source available that causes this error? Is it just running `cargo bench` on a fresh repo?

**Comment by ssh352** [comment]
> There's not much we can do about this in rkyv, we should minimize this and report it upstream at https://github.com/rust-lang/rust. Do you have source available that causes this error? Is it just running `cargo bench` on a fresh repo?

just running cargo bench, rustc 1.68.2 on Darwin

**Comment by djkoloski** [comment]
Closing since this is an upstream issue.
