### ISSUE TITLE
Question: how to apply archive_* with custom archive?

### ISSUE THREAD

**Issue by kwonoj** [rkyv/rkyv#380]
Sorry for the potentially dumb q:

I'm trying to enable bytecheck against structs with custom archive type without `#[derive(..)]`, i.e

```
#[archive(check_bytes)]
#[archive_attr(repr(C))]
pub struct EncodeBigInt;

impl rkyv::with::ArchiveWith<Box<BigIntValue>> for EncodeBigInt {
...
}

impl<S> rkyv::with::SerializeWith<Box<BigIntValue>, S> for EncodeBigInt
where
    S: ?Sized + rkyv::ser::Serializer {
...
}

impl<D> rkyv::with::DeserializeWith<rkyv::Archived<String>, Box<BigIntValue>, D> for EncodeBigInt
where
    D: ?Sized + rkyv::Fallible {
...
}
```

unlike derived struct, this raises

```
error: cannot find attribute `archive` in this scope
error: cannot find attribute `archive_attr` in this scope
```

Is there an example I can enable bytecheck for those struct?

**Comment by djkoloski** [comment]
In this case, you'll want to use bytecheck's derive macros directly. For example:

```rust
#[derive(rkyv::bytecheck::CheckBytes)]
pub struct ArchivedBigIntValue { ... }
```

That should generate the validation code for your archived type. It should compose nicely with your `rkyv::with` code as well.

**Comment by kwonoj** [comment]
Not sure what I'm doing wrong, but that gives me this instead:

```
 1  error[E0432]: unresolved import `bytecheck`
    |
 83 | #[derive(rkyv::bytecheck::CheckBytes)]
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: a similar path exists: `rkyv::bytecheck`
    |
    = note: this error originates in the derive macro `rkyv::bytecheck::CheckBytes
```

Also, how to apply `archive_attr`?

**Comment by djkoloski** [comment]
When you write an `ArchiveWith` impl, you use two types. The first is the wrapper type, which you already have. The second is the custom archived type that it selects. This is the `type Archived ...` type that's part of your `ArchiveWith` impl. That is the type that you're trying to apply the effects of `archive(check_bytes)` and `archive_attr(repr(C))` to. For `archive(check_bytes)`, you can just `#[derive(rkyv::bytecheck::CheckBytes)]` on that `Archived` type (note: rkyv only exports its bytecheck dependency relatively recently, you may need rkyv 0.7.40 or later). For `archive_attr(repr(C))`, that just turns into `#[repr(C)]` on the same type. So:

```rust
#[derive(rkyv::bytecheck::CheckBytes)]
#[repr(C)]
pub struct ArchivedBigIntValue { ... }

pub struct EncodeBigInt;

impl rkyv::with::ArchiveWith<Box<BigIntValue>> for EncodeBigInt {
    type Archived = ArchivedBigIntValue;
    ...
}
```

**Comment by djkoloski** [comment]
I think this pain point has been mostly resolved by the addition of `#[archive(check_bytes)]`.
