### ISSUE TITLE
Unable to use ArchivedHashmap with string tuple as key

### ISSUE THREAD

**Issue by GeeWee** [rkyv/rkyv#391]
Hey. I love rkyv - it's a wonderful project and I use it extensively.

I'm not sure if this is a feature request or me being dumb. I have a Hashmap with string tuple keys and an irrelevant payload
```rust
// This compiles
let map: ArchivedHashMap<ArchivedString, i32> = foo();
let value = map["foo"];
let value = map.get("foo");

// This does not
let map: ArchivedHashMap<(ArchivedString, ArchivedString), i32> = get_map();
let value = map[("foo", "bar")];
let v = map.get(("foo", "bar"));
```

Is there some sort of magic I need to do, or is it impossible to borrow an tuples of ArchivedStrings from tuples of strings, even though the borrowing of non-tuple variants work?

(I can of course concatenate the strings somehow in the meantime, but it's not quite as nice)

**Comment by GeeWee** [comment]
Yeah I also tried implementing `Borrow<&str, &str>` and I agree it doesn't seem possible.

Another escape hatch would be to allow the easy creation of an ArchivedString from a &str, but it doesn't seem possible to that currently (I'm only able to create an `&ArchivedString` which doesn't allow me to index)

**Comment by djkoloski** [comment]
This is now possible via the `*_with` APIs on `ArchivedHashMap` in 0.8.
