### ISSUE TITLE
Custom access APIs for archived maps

### ISSUE THREAD

**Issue by djkoloski** [rkyv/rkyv#392]
`ArchivedHashMap`, `ArchivedBTreeMap`, and other key-bearing data structures struggle with nontrivial keys because of the `K: Borrow<Q>, Q: Hash + Eq + ?Sized` bounds. It's not always possible to implement `Borrow`, so a custom comparison function would be a nice escape hatch. I propose something like:

```rust
fn get_with<Q: Hash + Eq + ?Sized, F: Fn(&K, &Q) -> bool>(&self, key: &Q, compare: F) -> Option<&V>
```

for `ArchivedHashMap`, with a similar API for other structures.

See issue #391 for more context.

**Comment by GeeWee** [comment]
In this situation, what would the comparator function be there for if the method also takes in a key?

**Comment by djkoloski** [comment]
The `compare` function would be used to test `key` against the keys in a hash map that got sent to the same bucket. The lookup algorithm is to 1. hash `key` 2. look up the corresponding bucket for the hash 3. find an entry in the bucket which compares equal to `key`.

**Comment by GeeWee** [comment]
Right, yes that makes sense seeing as we can't compare the keys directly.

**Comment by GeeWee** [comment]
I have a first draft of the `get_with` method over at #396, but I have a few questions regarding the implementation I'd love some help with.

**Comment by GeeWee** [comment]
The PR is ready for a review now :)
