### ISSUE TITLE
Write example for backwards compatbility via enums

### ISSUE THREAD

**Issue by crwn1337** [rkyv/rkyv#393]
Is there anyway to do backwards compatibility for enums? a short example:
```rust
pub struct V1 {
    pub label: String,
}

pub struct V2 {
    pub label: String,
    pub password: String,
}

pub struct Latest {
    pub label: String,
    pub password: String,
    pub destination: String,
}

pub enum Door {
    V1(V1),
    V2(V2),
    Latest(Latest),
}

pub fn v1_to_v2(door: V1) -> V2 {
    V2 {
        label: door.label,
        password: "".to_string(),
    }
}

pub fn v2_to_latest(door: V2) -> Latest {
    Latest {
        label: door.label,
        password: door.password,
        destination: "".to_string(),
    }
}

pub fn is_latest(door: &Door) -> bool {
    matches!(door, Door::Latest(_))
}

pub fn any_to_latest(door: Door) -> Door {
    match door {
        Door::V1(door) => {
            let door = v1_to_v2(door);
            let door = v2_to_latest(door);
            Door::Latest(door)
        }
        Door::V2(door) => {
            let door = v2_to_latest(door);
            Door::Latest(door)
        }
        Door::Latest(door) => Door::Latest(door),
    }
}
```

or is there a better way to do this? Adding a bigger struct to Door and trying to deserialize an older version of it fails.

**Comment by djkoloski** [comment]
Have you seen this example? https://github.com/rkyv/rkyv/blob/master/examples/backwards_compat/src/main.rs

**Comment by crwn1337** [comment]
> Have you seen this example? https://github.com/rkyv/rkyv/blob/master/examples/backwards_compat/src/main.rs

I guess a better example would be this:
```rust
pub enum Test {
    A(u16),
    B(u32),
}

pub fn main() {
    let test = Test::A(1);

    let mut serializer = AllocSerializer::<0>::default();
    serializer.serialize_value(&test).unwrap();
    let bytes = serializer.into_serializer().into_inner();

    println!("{:?}", bytes);
}
```
would print:
```
[0, 0, 1, 0, 0, 0, 0, 0]
```
however, if I add another element that increases the size of the enum:
```rust
pub enum Test {
    A(u16),
    B(u32),
    C(u64)
}

pub fn main() {
    // bytes from above
    let bytes: [u8; 8] = [0, 0, 1, 0, 0, 0, 0, 0];
    let archived = rkyv::check_archived_root::<Test>(&bytes[..]).unwrap();
    let deserialized: Test = archived.deserialize(&mut rkyv::Infallible).unwrap();

    println!("{:?}", deserialized);
}
```

it will fail to deserialize:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ContextError(ArchiveError(OutOfBounds { base: 0x7dcb6ff6e8, offset: -8, range: 0x7dcb6ff6e8..0x7dcb6ff6f0 }))', src\main.rs:199:66
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\rust-tests.exe` (exit code: 101)
```

i hope this makes it more clear.

**Comment by djkoloski** [comment]
When the `C` variant is added to `Test`, the size of `Test` increased from `size_of::<Discriminant>() + size_of::<u32>()` to `size_of::<Discriminant>() + size_of::<u64>()`. This breaks binary compatibility because even though the first two variants haven't changed, the overall enum has and rkyv checks for enough memory for an `ArchivedTest` _before_ checking the enum discriminant. One way to work around this is to make sure that the size of `Test` never increases by boxing all of your enum fields:
```rust
#[derive(Archive, Serialize, Deserialize)]
pub enum Test {
    A(#[with(AsBox)] u16),
    B(#[with(AsBox)] u32),
    C(#[with(AsBox)] u64),
}
```
This isn't 100% perfect because if you add enough variants to increase the size of the discriminant, the size of the enum may change. But it should be good enough in most cases.

**Comment by djkoloski** [comment]
The discriminants for archived enums are now required to always be a single byte, so the previous example is now comprehensive. The linked example (`backwards_compat.rs`) looks comprehensive enough to describe how to add backwards compatibility support to your data format. Closing this as complete.
