### ISSUE TITLE
Question: does zero-copy deserialization change object performance?

### ISSUE THREAD

**Issue by vigna** [rkyv/rkyv#394]
I have looked carefully in the manual, but I couldn't find whether there is an impact on the performance of a zero-copy deserialized object WRT a normal object of the same type with the same content.

The author of zerovec, for example, shows that there is definitely a gap in his implementation. I guess in the case of rkyv resolving relative pointers might have some impact, as the immutability of the backing storage make it necessary to solve them at each access, but it would be nice to know if the effect is negligible or not.

**Comment by djkoloski** [comment]
rkyv strives to have exactly the same formal runtime for serialized types as regular ones - you should expect there to only be a constant factor differentiating the runtimes of the two. I think it's worth mentioning that runtime may vary in the docs, but I really cannot say what the impact is likely to be. In most cases (x86?) you'll probably pay a small tax, other targets (ARM? it seems likely that relative pointers will cost more on RISC architectures) may pay a higher tax. Performance is a highly composite metric though, and I don't want to make claims that are hard to back up or require updating over time.
