### ISSUE TITLE
Document alignment requirements for accessing byte slices

### ISSUE THREAD

**Issue by w-flo** [rkyv/rkyv#399]
Thank you for rkyv, it's a great tool!

I have stumpled upon this comment: https://github.com/rkyv/rkyv/issues/382#issuecomment-1520017285
> An alignment of 4-16 is usually required, which you can get with rkyv's `AlignedVec` container. This alignment invariant is a safety condition of `archived_root` and is checked by `check_archived_root`.

Looking at the [docs](https://docs.rs/rkyv/latest/rkyv/util/fn.archived_root.html) for `archived_root`, it only lists "byte slice must represent an archived object" and "root object must be stored at the end of the slice" as safety preconditions. So I thought that using `rkyv::to_bytes` to serialize something, then storing the returned bytes in a file, then later reading the bytes from the file as a `Vec<u8>` (shouldn't be an issue when mmaping the file, as that is something like 4096-byte aligned) and passing them into `archived_root` would be okay. However, now I think that's unsound, because the Vec might not be 16-byte aligned.

So I do wonder what exactly the alignment requirements are in this situation. I think adding a bullet point to the `archived_root` docs might be useful? Is it sufficient to use `AlignedVec`, or are there cases where the alignment needs to be even larger than 16? Maybe the same question arises for the `from_bytes_unchecked` function.

For context, my application caches some data (supplied by myself) using rkyv, so it's not at risk of "serialized rkyv data injection", so I don't use the validation feature. I'd still like to use the rkyv API correctly under the "I can trust that the bytes in the file are from `rkyv::to_bytes`, using the same rkyv struct definitions" assumption.

**Comment by djkoloski** [comment]
I don't know of any more highly-aligned types off the top of my head, but it's possible that types in the standard library will have a higher alignment than 16.

**Comment by djkoloski** [comment]
I ended up making the safety docs for the unchecked variants of these functions more vague, both because the safety requirements are already very vague (e.g. "the given position must have a valid archived type"), and also because validation should always be the source of truth for us. In return, I improved the debug assert for buffer unalignment so that it now suggests enabling the `unaligned` feature. Done in 5e5a3e8bc4b3d11678368348975da8f6adaded64

**Comment by w-flo** [comment]
Thank you! This does solve the issue.

I feel like it also makes it pretty difficult to use rkyv without the validation feature in a "serious environment", because who knows what `from_bytes` actually does without spending a lot of time to read and understand the source, and then make sure it is still the same on every rkyv update. Just using the `from_bytes` call for testing is not good enough in that case, because maybe some factor just randomly happens to be fine in 99.9999% of cases and then lead to a serious bug in one rare situation.

In my hobby project, it doesn't really matter though! So I'll just keep using the unsafe unchecked functions and assume that my current implementation, which is "just pass in all the bytes that I got from serialization using a semver-compatible rkyv version, and make sure the bytes are aligned to at least the target struct's alignment", will be fine.

**Comment by djkoloski** [comment]
Just to follow up:

> who knows what from_bytes actually does without spending a lot of time to read and understand the source

This is kind of the point. The archived types' implementations of `CheckBytes` are effectively implementation details; the "public API" is limited to the serialized bytes and whether `check_bytes` returns `Ok`.

> and then make sure it is still the same on every rkyv update

There are two components to this:
- You can avoid re-checking data, but rkyv leaves that to you to figure out. For some use cases, it's safe to just assume the data is valid. For others, a version number or checksum is good enough. For yet others, a cryptographic signature is sufficient. And in the worst case, you do just have to validate data every time. It's up to you to determine the right strategy for your use case and implement it.
- As of 0.8, rkyv promises that the types it provides will have the same serialized representation for every semver-compatible version. So you're now guaranteed that if the types and bytes don't change, then you can skip subsequent validation.
