### ISSUE TITLE
Provide macros to derive rkyv traits on foreign types

### ISSUE THREAD

**Issue by mkatychev** [rkyv/rkyv#400]
```rust
// https://docs.rs/tracing-core/0.1.30/src/tracing_core/metadata.rs.html#501-535
// impl Level {
//     pub const ERROR: Level = Level(LevelInner::Error);
//     pub const WARN: Level = Level(LevelInner::Warn);
//     pub const INFO: Level = Level(LevelInner::Info);
//     pub const DEBUG: Level = Level(LevelInner::Debug);
//     pub const TRACE: Level = Level(LevelInner::Trace);
// }

#[derive(Eq, PartialEq, Debug, rkyv::Serialize, rkyv::Deserialize, rkyv::Archive)]
#[archive_attr(derive(Debug))]
#[archive(compare(PartialEq), check_bytes)]
struct MyLevel(tracing::Level);

fn main() {}
```
Attempting to compile the code above produces the error below:
```
  --> src/lib.rs:10:68
   |
10 | #[derive(..., rkyv::Archive)]
   |               ^^^^^^^^^^^^^ the trait `Archive` is not implemented for `Level`
```
There has been mentions of [foreign type support](https://github.com/rkyv/rkyv/issues/238) however I'm struggling at finding a clean solution that does not use unsafe code. I would be perfectly happy with intermediate types specified with [attribute tags similar to serde](https://serde.rs/container-attrs.html#into):
```rust
struct ArchivedLevel(u8);
impl From<tracing::Level> for ArchivedLevel {
    fn from(level: tracing::Level) -> Self {
        ArchivedLevel(match level {
            tracing::Level::TRACE => 0,
            tracing::Level::DEBUG => 1,
            tracing::Level::INFO => 2,
            tracing::Level::WARN => 3,
            tracing::Level::ERROR => 4,
        })
    }
}

#[rkyv(into = "ArchivedLevel")]
struct MyLevel(tracing::Level);
```

Is there a pattern documented for this or any current issues/units of work for this?

**Comment by djkoloski** [comment]
It's not documented, but the typical approach is either:

- Newtype the foreign type and manually implement `Archive` on that
- Or write a "with" type and apply it to the foreign type (see [this example](https://github.com/rkyv/rkyv/blob/master/examples/opcode/src/main.rs) of writing a "with" type)

As for not requiring unsafe code, I'm not sure if that will be easy to do without access to the derive. However, if you can turn your type into bytes safely, then you might be able to do it.

I like the pattern you describe wanting, though there is one significant blocker to enabling it. Because rkyv does two-phase serialization, it needs the serializing value during both phases. However, there's not a good way to persist a converted value. So in most cases, you'd need to do the conversion twice which would be excess work and slow things down.

I think this problem could be avoided by wrapping the converted type in an `ArchivedBox`, as the value could be converted, serialized, and resolved all during the serialize phase of the box. This isn't ideal either though, since the extra indirection takes up additional space on the wire.

**Comment by mkatychev** [comment]
> Because rkyv does two-phase serialization
Are you referring to `rkyv::Serialize` and `rkyv::Archive` here?

> However, there's not a good way to persist a converted value.
How long would a value need to persist here? I wonder if passing in some sort of memoization table would help 🤔:
* something global `static ref MEMOMAP: Mutex<HashMap<_, _>>`) 
* or passing it in explicitly similar to how [zig explicitly passes around allocators](https://ziglearn.org/chapter-2/#allocators)

Indirection may be overkill for foreign types that can be masked as primitives.

**Comment by djkoloski** [comment]
> Are you referring to `rkyv::Serialize` and `rkyv::Archive` here?

Yes

> I wonder if passing in some sort of memoization table would help

That's one potential solution! The right way to pass it through is using the serializer. You'd want to add a trait to capture the specific functionality and then impl rkyv's traits only on those serializers.

In this case where the foreign types are simple primitives, it probably doesn't hurt to convert twice. I just meant this pattern should be avoided _in general_, it seems fine to convert twice in this case.

**Comment by cakekindel** [comment]
as a strawman, here's a repo with the 2 solutions mentioned (which compile and behave as expected)
- custom `With` type [link :link:](https://git.orionkindel.com/orion/rkyv_foreign_type_demo/src/branch/main/src/foo_with.rs)
- boilerplate-heavy intermediate type closer to the actual bytes off the wire [link :link:](https://git.orionkindel.com/orion/rkyv_foreign_type_demo/src/branch/main/src/foo_ir.rs)
- an imaginary derive macro attribute allowing a (safe) free function of `Fn(<field>) -> <some type that impls Archive>` to bypass the Archive trait impl requirement [link :link:](https://git.orionkindel.com/orion/rkyv_foreign_type_demo/src/branch/main/src/foo_imaginary.rs)

if the syntax / ux of that derive attribute is something we'd like in the core library i'd be happy to take a stab at implementing it :)

**Comment by cakekindel** [comment]
definitely would love a high-level abstraction like the one i described which could just desugar to a custom `ArchiveWith` type

**Comment by MaxOhn** [comment]
Here's a gist of how one can defer `*With` impls to a wrapper by introducing some intermediate traits:
https://gist.github.com/MaxOhn/f5e2ea72f745f7c9ddec7d4963a6042d

Essentially, you define a new type, implement `ToArchivable` (and `DeserializeWith` if needed) manually, and then annotate fields with `#[with(WithConvert<MyType>)]` for `Archive` derives.

Realistically, this procedure could live in its own crate and be pulled in as dependency to abstract away all `unsafe` in a safe manner.

PS: There is my [`rkyv-with`](https://crates.io/crates/rkyv-with) crate that provides `ArchiveWith` and `DeserializeWith` derive macros but it's utility doesn't cover all cases. For this issue specifically, it would require `Level`'s inner type `LevelInner` to have some publicly available way of turning it into- and creating it from something archivable, which is not the case so it can't be used.

**Comment by simgt** [comment]
I'm facing the same wall with [slotmap](https://docs.rs/slotmap/latest/slotmap/index.html#custom-key-types)'s keys. The underlying type is a struct containing two u32 and has the equivalent of `to_u64` and `from_u64` .

> as a strawman, here's a repo with the 2 solutions mentioned (which compile and behave as expected) and a hypothetical third
> 
> * custom `With` type [link 🔗](https://git.orionkindel.com/orion/rkyv_foreign_type_demo/src/branch/main/src/foo_with.rs)
> * boilerplate-heavy intermediate type closer to the actual bytes off the wire [link 🔗](https://git.orionkindel.com/orion/rkyv_foreign_type_demo/src/branch/main/src/foo_ir.rs)
> * an imaginary derive macro attribute allowing a (safe) free function of `Fn(<field>) -> <some type that impls Archive>` to bypass the Archive trait impl requirement [link 🔗](https://git.orionkindel.com/orion/rkyv_foreign_type_demo/src/branch/main/src/foo_imaginary.rs)
> 
> if the syntax / ux of that derive attribute is something we'd like in the core library i'd be happy to take a stab at implementing it :)

Very nice, thanks @cakekindel 🙌 However in your version with `With` I don't understand when `TracingLevel::try_from_u8` would be called. My understanding from the documentation was that `to_u8` and `from_u8` would be called in `Serialize` and `Deserialize` respectively, but I'm not sure where the cast of the archived version would occur 😵‍💫

**Comment by djkoloski** [comment]
rkyv supports remote derive as a first-class feature now
