### ISSUE TITLE
Clarification: is it possible to call a method of a type on the archived version?

### ISSUE THREAD

**Issue by vigna** [rkyv/rkyv#405]
I realize this is a very basic question, but we could not find this specific issue clarified in the documentation. Looking at the derived code for the archived version, we find no trace of the methods of our structure. Is it necessary to reimplement them on the archive version? There's an "Impl duplication" chapter in the book, but the link is ghosted.

**Comment by djkoloski** [comment]
Sorry for the confusion, the "Impl duplication" chapter is intended to cover this problem. All of the "ghosted" links are pages that haven't been written yet.

When rkyv generates the archived version of a type, it isn't able to apply the existing methods you've written to it. Those impls are all restricted to the original type. In most cases, the impls you have written for the original type can be translated for the archived type without changing anything. For example:

```rust
#[derive(Archive, Serialize, Deserialize)]
struct Foo {
    inner: String,
}

impl Foo {
    pub fn print_inner(&self) {
        println!("My inner is '{}'", self.inner);
    }
}

impl ArchivedFoo {
    pub fn print_inner(&self) {
        println!("My inner is '{}'", self.inner);
    }
}
```

Note how the two impl blocks are identical except for the type being impl'd for.

**Comment by vigna** [comment]
I think this is a fundamental issue and should be covered in the introduction. "Zero-copy deserialization" means, to everybody, "deserialization without copying", not "I'll give you another type without copying".

**Comment by Nickersoft** [comment]
@djkoloski I've just run up against this issue myself, and my method body is a lot longer than the simple example from the docs. 

Is there any way I could leverage traits, unions, or generics to reduce code duplication so I'm not copying and pasting the entire method body?

**Comment by djkoloski** [comment]
Can you use a macro to write simultaneous impls? I'm not sure if that falls under the "copying and pasting" you want to avoid.

**Comment by Nickersoft** [comment]
> Can you use a macro to write simultaneous impls? I'm not sure if that falls under the "copying and pasting" you want to avoid.

Hmm.. could you give an example? I'm a bit familiar with macros but unsure how I can use  them to reuse logic across types

**Comment by djkoloski** [comment]
Most of the time, you can use rkyv's types just the same as normal ones. So you may be able to use a macro to write what you want:

```rust
macro_rules! impl_all{
    ($($tys:ty),*) => {
        $(
            impl<..> Foo for $ty {
                fn foo(&self) {
                    println!("My value is {}", self.value);
                }
            }
        )*
    }
}

impl_all!(Foo, ArchivedFoo);
```

This is a pretty crude macro but with some work I expect you'd be able to support putting the impl code directly in the macro invocation.

**Comment by Nickersoft** [comment]
Interesting! I may have to read up on macros to better understand the syntax 😅 One thing that's tripping me up though is that my macro will need to deal with return types... so in this example, assuming I'm archiving `MyStruct`, `foo` would return `MyValue` for `MyStruct` and `ArchivedMyValue` for `ArchivedMyStruct`. 

Would you need to use generics somehow?

**Comment by vigna** [comment]
BTW, that's why we created [epserde](https://crates.io/crates/epserde). We prefer a little bit of effort in the design of the structure in exchange for guaranteed zero performance cost, and getting back the original structure.

**Comment by djkoloski** [comment]
I'm glad that fit your use case and hope others with similar use cases find value in your project. However, this is not the right place to promote your project. Please limit discussion here to rkyv.

**Comment by djkoloski** [comment]
> @djkoloski Interesting! Thanks for the example :) I may have to read up on macros to better understand the syntax 😅
> 
> One thing that's tripping me up though is that my macro will need to deal with return types... so in this example, assuming I'm archiving `MyStruct`, `foo` would return `MyValue` for `MyStruct` and `ArchivedMyValue` for `ArchivedMyStruct`.
> 
> Would you need to use generics somehow in the macro or something?

You could use generics, I think that might be a little cumbersome compared to just using more macro parameters but if you can find a way to make it work then it's worth a shot. I think you'd need something like:

```rust
pub trait MyInterface {
    type ReturnType;
}

impl MyInterface for MyStruct {
    type ReturnType = MyValue;
}

impl MyInterface for ArchivedMyStruct {
    type ReturnType = ArchivedMyValue;
}
```

That would let you write `fn foo(&self) -> <Self as MyInterface>::ReturnType` uniformly, though it is quite cumbersome.

**Comment by vigna** [comment]
> I'm glad that fit your use case and hope others with similar use cases find value in your project. However, this is not the right place to promote your project. Please limit discussion here to rkyv.

I apologize. I removed the post.

**Comment by Nickersoft** [comment]
> > @djkoloski Interesting! Thanks for the example :) I may have to read up on macros to better understand the syntax 😅
> > 
> > One thing that's tripping me up though is that my macro will need to deal with return types... so in this example, assuming I'm archiving `MyStruct`, `foo` would return `MyValue` for `MyStruct` and `ArchivedMyValue` for `ArchivedMyStruct`.
> > 
> > Would you need to use generics somehow in the macro or something?
> 
> You could use generics, I think that might be a little cumbersome compared to just using more macro parameters but if you can find a way to make it work then it's worth a shot. I think you'd need something like:
> 
> ```rust
> pub trait MyInterface {
>     type ReturnType;
> }
> 
> impl MyInterface for MyStruct {
>     type ReturnType = MyValue;
> }
> 
> impl MyInterface for ArchivedMyStruct {
>     type ReturnType = ArchivedMyValue;
> }
> ```
> 
> That would let you write `fn foo(&self) -> <Self as MyInterface>::ReturnType` uniformly, though it is quite cumbersome.

Ah, my bad - I just meant is there a way to adapt your macro implementation to account for the different return types? Or would you just use multiple macro invocations and pass the return types in as an additional parameter?

Perplexity gave me this approach:

```rust
macro_rules! implement_bar { 
  ($struct:ident, $return_type:ty) => { 
    impl $struct { 
      fn bar(&self) -> $return_type { 
        // Your shared logic here 
      } 
    } 
  }; 
} 

implement_bar!(MyStruct, Value);
implement_bar!(ArchivedStruct, ArchivedValue);
```
