### ISSUE TITLE
Add documentation on how to use `AllocationTracker`

### ISSUE THREAD

**Issue by stevenliebregt** [rkyv/rkyv#406]
The docs say to use the ScratchTracker to get a good estimate for scratch space but does not explain how to use it.

**Comment by MaxOhn** [comment]
The easiest way is to use a [`CompositeSerializer`](https://docs.rs/rkyv/latest/rkyv/ser/serializers/struct.CompositeSerializer.html), wrap your scratch in a [`ScratchTracker`](https://docs.rs/rkyv/latest/rkyv/ser/serializers/struct.ScratchTracker.html), serialize an instance with that serializer, and then check [`ScratchTracker::min_buffer_size`](https://docs.rs/rkyv/latest/rkyv/ser/serializers/struct.ScratchTracker.html#method.min_buffer_size) to see how much scratch space was required.

This test can serve as example: https://github.com/rkyv/rkyv/blob/58587fdf527546bedd593c649b889898c3266daf/rkyv_test/src/test_alloc.rs#L2141-L2186

**Comment by djkoloski** [comment]
Added a new section for this in 6c2e1e762e70ee07bd6b25c8f31ff0d36dcda283.
