### ISSUE TITLE
Seahash has poor performance with integer keys

### ISSUE THREAD

**Issue by Amanieu** [rkyv/rkyv#412]
My performance profile has ~4% spent in `<seahash::stream::SeaHasher as core::hash::Hasher>::write` and ~2% spent in `<seahash::stream::SeaHasher as core::hash::Hasher>::finish`, despite using a `HashMap` with a simple `u64` key. 

With a different hasher such as AHash or FxHash, this whole process consists of just a handful of instructions (~5) which are inlined directly into the hash table lookup function.

Changing the hasher would be a breaking change in the rkyv format, but perhaps this could be considered under a feature flag?

**Comment by djkoloski** [comment]
I think that's sensible to provide as a feature flag. Do you know whether AHash or FxHash are portable across platforms? The primary motivation for choosing seahash was its strong guarantee to get the same hash from the same data on all platforms.

**Comment by Amanieu** [comment]
Unfortunately not. FxHash produces different results on 32-bit vs 64-bit platforms, and aHash uses AES instructions when available which produces a completely different hash.

Perhaps the 64-bit variant of FxHash could be directly included in rkyv? HashDoS guarantees aren't needed since perfect hashing is used (though it might still hurt serialization time).

**Comment by djkoloski** [comment]
As long as `FxHasher64` always gives the same results regardless of the target platform, it's fine to include.

**Comment by djkoloski** [comment]
Wrote an implementation of fxhash with accommodations that should produce the same hash on all platforms in be38ebe926bf8bb4898af472ba7ce90f72df74bd
