### ISSUE TITLE
Compare ArchivedString against Cow<'_, str>

### ISSUE THREAD

**Issue by tv42** [rkyv/rkyv#421]
I have

```rust
#[derive(rkyv::Serialize, rkyv::Archive, rkyv::Deserialize, Debug)]
#[archive(check_bytes)]
#[archive_attr(derive(Debug))]
pub struct Example {
    pub name: String,
}
```

```rust
struct Thing<'a> {
   x: Cow<'a, str>,
}
```

and `fn lookup(&self, thing: &Thing) ...`

What I wanted to do was `archived_example.name == thing.x`, but that doesn't compile:

```
error[E0277]: can't compare `ArchivedString` with `Cow<'_, str>`
  --> foo.rs:94:34
   |
94 |             if archived_example.name == thing.x
   |                                  ^^ no implementation for `ArchivedString == Cow<'_, str>`
   |
   = help: the trait `PartialEq<Cow<'_, str>>` is not implemented for `ArchivedString`
   = help: the following other types implement trait `PartialEq<Rhs>`:
             <ArchivedString as PartialEq>
             <ArchivedString as PartialEq<std::string::String>>
             <ArchivedString as PartialEq<str>>
             <ArchivedString as PartialEq<&str>>
```

Could ArchivedString also handle Cow, please?

Workaround: `archived_example.name.as_str() == thing.x`

**Comment by djkoloski** [comment]
May aggravate #434, I'm not opposed to an impl if it gets put behind `extra_traits`.

**Comment by djkoloski** [comment]
I'm predisposed to saying that your workaround is the intended solution here. We can't add impls for everything, and an extra `as_str()` is harmless. Closing as obsolete, but if this really does turn out to be a serious problem I can reconsider.
