### ISSUE TITLE
Add more examples in doctests and the book

### ISSUE THREAD

**Issue by mintlu8** [rkyv/rkyv#424]
The examples for Rkyv exists only in the readme.md and the repository, while few and far between in docs.rs and the book for this project. It would be easier for newcomers to learn this crate if one or both of these sources provide some examples early on.

**Comment by kaimast** [comment]
I am trying to understand rkyv right now and have quite a hard time to understand how to use the API from the few examples given. 
There are also some inconsistencies. For example, the README mentions `rkyv::Infallible` which seems to have been removed in 0.8.

**Comment by djkoloski** [comment]
All of the core APIs now have associated examples (`access`, `serialize`, `deserialize`, etc). The book will be updated with some more information soon.

**Comment by djkoloski** [comment]
Fleshed out some more of this in the book in 6c2e1e762e70ee07bd6b25c8f31ff0d36dcda283. Feel free to file separate issues if you have specific examples in mind.
