### ISSUE TITLE
ahash 0.7 yanked

### ISSUE THREAD

**Issue by dfeyer** [rkyv/rkyv#437]
The current released version of rkyv is not installable, because ahahs 0.7 (dependency of hashbrown) has been yanked. Look like that you upgrade hashbrown to 0.14 who solve the issue (at least 0.14.2), but this is not released actually.

**Comment by djkoloski** [comment]
Related: https://github.com/tkaitchuck/aHash/issues/174

This isn't really rkyv's fault but I'll do what I can to help the situation. It sounds like we'd need to backport a `hashbrown` bump to 0.14, but that's a semver-breaking change unfortunately. According to [this comment](https://github.com/tkaitchuck/aHash/issues/163#issuecomment-1776107904) it sounds like you may be able to install a yanked version of ahash with the `--locked` argument.

**Comment by dfeyer** [comment]
> to install a yanked version of ahash with the `--locked` argument.

Thanks for your fast answer. I know the trick for the locked argument, but when you start a new project you are kind of ... lost as you don't have lock file.

**Comment by tkaitchuck** [comment]
0.7.7 has now been published. It contains a patch.

**Comment by djkoloski** [comment]
Thank you for your hard work!
