### ISSUE TITLE
Building on ESP32 fails because has_atomics_64 is wrongly set

### ISSUE THREAD

**Issue by ProfFan** [rkyv/rkyv#441]
In `build.rs` RKYV checks a blacklist and set all other platforms to have 64-bit atomics. Unfortunately the ESP32 (Xtensa 32-bit) does not have 64b atomics and fails to build.

**Comment by ProfFan** [comment]
#442

**Comment by ProfFan** [comment]
more crates need to be patched including `rend` `bytecheck` with the same patch

**Comment by djkoloski** [comment]
Now that `target_has_atomic` is stable, this has been fixed for 0.8 in the main branch (and for all associated crates).
