### ISSUE TITLE
Write example for using remote derive

### ISSUE THREAD

**Issue by ezkangaroo** [rkyv/rkyv#446]
Hello, I'm trying to use `rkvy` in a `struct` which has custom type coming from external library, which provides custom serialize/deserialize, but not sure how to wire them. Here is example Code.

```rust 
#[derive(Clone, Serialize, Deserialize, PartialEq, Archive)]
pub struct Store {
   pub id: i32,

   pub looker: SomeCustomLooker // coming from external library <- how to use custom functions here??
}
```

As it happens, external library is providing this functions: 

```rust
serialize(val: SomeCustomLooker) -> Vec<u8>
deserialize(val: Vec<u8>) -> Result<SomeCustomLooker, ....>
```

In `serde` and `bincode`, I can do

```rust
#[derive(Clone, Serialize, Deserialize, PartialEq)]
pub struct Store {
   pub id: i32,

    #[serde(
        serialize_with = "serialize_looker",
        deserialize_with = "deserialize_looker"
    )]
   pub looker: SomeCustomLooker // coming from external library
}
```

but not sure, how to tackle this with `rkvy`.

**Comment by djkoloski** [comment]
rkyv has a related but different system for serializing external types called [wrapper types](https://rkyv.org/wrapper-types.html). The book documentation is somewhat sparse, so I encourage you to read the [example](https://docs.rs/rkyv/latest/rkyv/with/trait.ArchiveWith.html#example) for `ArchiveWith`. It's basically a way to let you manually write impls for external types as long as you add an attribute.

**Comment by djkoloski** [comment]
As of #544, rkyv 0.8 will now support remote derive (thanks @MaxOhn!). Updating the name of this issue.
