### ISSUE TITLE
tinyvec::TinyVec impls not accessible in 0.7.42 release

### ISSUE THREAD

**Issue by silvanshade** [rkyv/rkyv#450]
It seems that the various `rkyv` impls are not accessible for `tinyvec::TinyVec` in the `0.7.42` release.

They are feature gated behind `"tinyvec_alloc"` (see [here](https://github.com/rkyv/rkyv/blob/4645bf686ffc142c45c3be652247d13e54288f70/rkyv/src/impls/tinyvec.rs#L73)) but that feature isn't defined in the Cargo manifest.

Would it be possible to fix that and make a quick patch release?

I've created a branch here with the respective changes: https://github.com/silvanshade/rkyv/tree/feature/tinyvec_alloc

**Comment by djkoloski** [comment]
This should be fixed in `0.7.43`. Enable the `tinyvec` feature and the `alloc` features at the same time to enable those impls.
