### ISSUE TITLE
Mutability of archives?

### ISSUE THREAD

**Issue by XavDesbordes** [rkyv/rkyv#459]
Hi,
Is it possible to mutate a u64 field of an archive in-place without deserializing first ?

like mutating the `how` field of a non deserialized archive for performance reasons?
```
#[derive(Archive, Deserialize, Serialize, Default)]

struct Strt {
    what: String,
    how: u64,
    hm: Hm,
}

#[derive(Archive, Deserialize, Serialize, Default)]

struct MyStruct {
    vec: Vec<Strt>,
    p: u32,
}

```

Thanks

**Comment by djkoloski** [comment]
Yes, you can get mutable access to the structure by calling `archived_root_mut`. That will give you back a `Pin<&mut T::Archived>` which you can traverse and mutate through. If you need to traverse containers, you'll probably need to use the specialized (e.g. [`index_pin`](https://docs.rs/rkyv/latest/rkyv/vec/struct.ArchivedVec.html#method.index_pin)).

**Comment by XavDesbordes** [comment]
Thanks!

here is my try:
```
    const ARBITRARY_VALUE: u64 = 3;

    let mut buffer: MyStruct = Default::default();

    buffer.p = 55;

    for i in 0..ARBITRARY_VALUE {
        let mut s: Strt = Default::default();

        s.how = 65 + i;

        s.what = format!("Test {}", i);

        buffer.vec.push(s);
    }

    let mut u = rkyv::to_bytes::<MyStruct, 1024>(&buffer).unwrap();

    let mut z = unsafe { rkyv::archived_root_mut::<MyStruct>(Pin::new(u.as_mut())) };

    for i in z.vec.pin_mut_slice() {
        i.how += 100;
    }

    for i in z.vec.iter() {
        println!("{}", i.how);
    }
```

but `z.vec.pin_mut_slice()` doesn't exist. How to access it ? thanks a lot

**Comment by djkoloski** [comment]
I think you need to pin-project your `z.vec` access, for example by doing `z.map_unchecked_mut(|z| &mut z.vec)` and then calling `.pin_mut_slice()` on it. There is probably also a way to get pin projection code written for your archived type using a macro or derive, but I'm not very familiar with what the options are. It's common to write a helper method for doing this:

```rust
impl ArchievdMyStruct {
    pub fn vec_pin(self: Pin<&mut Self>) -> Pin<&mut ArchivedVec<...>> {
        unsafe { self.map_unchecked_mut(|s| &mut s.vec) }
    }
}
```

So then you can just call `z.vec_pin().pin_mut_slice()`.

**Comment by XavDesbordes** [comment]
Thanks, this is what I tried:

```
    let mut u = rkyv::to_bytes::<MyStruct, 1024>(&buffer).unwrap();

    let mut z = unsafe { rkyv::archived_root_mut::<MyStruct>(Pin::new(u.as_mut())) };

    unsafe {
        let mut v = z.as_mut().map_unchecked_mut(|z| &mut z.vec);

        let mut the_slice = v.pin_mut_slice();
        let result = &mut the_slice.index_mut(0);

        result.how += 5;
    };
    for i in z.vec.iter() {
        println!("{}", i.how);
    }
```

I am still welcomed with :
```
cannot borrow data in dereference of `Pin<&mut [ArchivedStrt]>` as mutable
trait `DerefMut` is required to modify through a dereference, but it is not implemented for `Pin<&mut [ArchivedStrt]>`
```

Also tried with the impl above, same error as above:
`for i in z.vec_pin().pin_mut_slice().iter_mut() {}`

It works perfectly fine if I deserialize first but performance suffer.

I don't know what is going on..

**Comment by XavDesbordes** [comment]
Apparently, even when reusing the code of [another issue](https://github.com/rkyv/rkyv/issues/322#issuecomment-1290840662) just modifying the last loop from:
```
for (k, v) in rkyv_map.iter() {
        ...
}

```
to 

```
for (k, v) in rkyv_map.iter_mut() {
        *v += 1;
 }
```
yields an error: no iter_mut.

Well, I will consider that what I want is not possible at the moment. I leave this issue open in case someone is able to make this work. But in the meantime, I will serialize/deserialize, take a perf hit because doing otherwise it is too obscure right now. :slightly_smiling_face:

But thanks a lot!

**Comment by XavDesbordes** [comment]
An finally, this is the working code:

```
    let o = unsafe { z.as_mut().vec_pin().pin_mut_slice().get_unchecked_mut() };

    for i in o.iter_mut() {
        i.how += 100;
    }

    for i in z.vec.iter() {
        println!("{}", i.how);
    }
```

It was a bit obscure, but that's the price of learning a language I guess.

Thanks for your support !
