### ISSUE TITLE
size_[16,32,64] features and library development

### ISSUE THREAD

**Issue by Sky9x** [rkyv/rkyv#460]
I am developing a data structures library, and I want to have optional support for rkyv.
So, I added rkyv to my Cargo.toml:
```toml
[dependencies.rkyv]
version = "0.7"
optional = true
default-features = false
```
My library is `no_std`, so I've disabled the default features.

However, `cargo build --all-features` no longer works, failing with:
> error: one of ["size_16", "size_32", or "size_64"] features must be enabled

Because these features are all mutually exclusive (exactly one must be enabled), my library should not be enabling any of them, to allow downstream consumers to choose the repr that they want.
However, that means that I can't build my code unless I pick one of these features.

I've tried also adding rkyv to my `[dev-dependencies]`, which does make `cargo build --all-features --all-targets` work (because `--all-targets` builds unit tests which pulls in dev deps).
However, I still can't do anything else (like build documentation etc) without adding `--features rkyv/size_32` to all of my commands, which is not ideal.
The best I've been able to do is add `__rkyv_hack = ["rkyv/size_32"]` to my crate `[features]`, which works, but is quite hacky.

Is there a better way to do this? Did I miss something in the documentation?

---

While this use case could probably benefit from [Pre-RFC: Mutually-excusive, global features](https://internals.rust-lang.org/t/pre-rfc-mutually-excusive-global-features/19618), such a concept doesn't currently exist :sob:

**Comment by djkoloski** [comment]
Unfortunately I don't have a good solution for this right now. One of the ideas that has been floated around was to have rkyv default to `size_32` when no other features are specified. I wonder if perhaps there's some setting in `.cargo/config.toml` that could turn a feature on only for your workspace?

**Comment by Sky9x** [comment]
I don't think thats a thing :cry:
Defaulting to `size_32` is probably the best solution. I can draft PR if that's something you're interested in.

**Comment by djkoloski** [comment]
I think it would be fine for rkyv to default to little-endian 32-bit relative pointers if there's no feature override. In that case, it would be nice if we could detect that we're being built for a binary target and emit a warning like "you didn't explicitly choose a pointer width and repr!". But I don't think we can do that either unfortunately.

**Comment by Sky9x** [comment]
I am bored; Draft PR opened https://github.com/rkyv/rkyv/pull/461

**Comment by Sky9x** [comment]
> it would be nice if we could detect that we're being built for a binary target and emit a warning like "you didn't explicitly choose a pointer width and repr!". But I don't think we can do that either unfortunately.
possibly with a build script and `println!("cargo:warning=foo bar");`?
