### ISSUE TITLE
Size prefix for the buffer ?

### ISSUE THREAD

**Issue by XavDesbordes** [rkyv/rkyv#463]
Hi,
Currently, I manually add a u32/u64 size prefix  (depending on context, always known in advance)  to my archives when storing on disk.

The afterthought is that I may access unaligned data while doing so, because I offset my archive by 4/8 bytes, which is problematic when I read u64 data in my archive. It forces the prefix to be a u64 to play safely.
Having the prefix size handled by the library could help dealing with that automatically.

So, Is there a "buffer length prefix mode" as flatbuffers do, already built in ?

Thanks,

**Comment by djkoloski** [comment]
The prefix mode you described does not exit in rkyv. How you get your bytes to rkyv is up to you, you just have to make sure the alignment is correct. Maybe in the future something like this could be useful, but it's a specific use case right now.
