### ISSUE TITLE
deterministic encoding?

### ISSUE THREAD

**Issue by cwbhhjl** [rkyv/rkyv#464]
Does rkyv guarantee that the same value will always be encoded into deterministic bytes? 

For example, deterministic field order, absence of random padding data for memory alignment, etc.

**Comment by djkoloski** [comment]
Some containers are inherently non-deterministic to serialize. `HashMap`s that contain the same keys may have different iteration orders, and so may serialize to different values. That said, rkyv does it's best to provide deterministic serialization. Field ordering is determined lexically for serialization. Padding bytes are present, but zeroed on the wire. By default, the compiler may choose to reorder fields within structs though, so you may want to enable the `strict` feature to ensure this doesn't happen.

**Comment by cwbhhjl** [comment]
Thank you for your response. I won't be using structures similar to HashMap, so it seems that under the strict feature, it can meet my requirements. I will do some tests. Thank you.
