### ISSUE TITLE
Current `main` head cannot build for no_std

### ISSUE THREAD

**Issue by mcclure** [rkyv/rkyv#468]
I am using rkyv in a configuration where I am using it to create rkyv serialized files in my `build.rs`, then include them in my executable with `include_bytes`. I am doing this to reduce memory/footprint on an embedded platform. As discussed in Discord 0.7 is struggling with my embedded platform (riscv32imafdc), so I was recommended to test with `main` branch (0.8-pre1). However when `std` is not enabled, `main` branch currently fails with many errors such as (excerpts)

```
error[E0432]: unresolved import `alloc::boxed`
 --> /home/mcc/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/e86ed9c/rkyv/src/impls/alloc/boxed.rs:7:20
  |
7 | use alloc::{alloc, boxed::Box};
  |                    ^^^^^ help: a similar path exists: `crate::alloc::boxed`
  |
  = note: `use` statements changed in Rust 2018; read more at <https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html>

error[E0412]: cannot find type `Box` in this scope
  --> /home/mcc/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/e86ed9c/rkyv/src/de/pooling/core.rs:16:12
   |
16 |         _: Box<dyn SharedPointer>,
   |            ^^^ not found in this scope
   |
help: consider importing one of these items
   |
1  + use alloc::boxed::Box;
   |
1  + use crate::de::pooling::Box;
   |

error[E0433]: failed to resolve: use of undeclared type `Vec`
   --> /home/mcc/.cargo/git/checkouts/rkyv-41442ee1b7a4be0a/e86ed9c/rkyv/src/ser/allocator/alloc.rs:140:26
    |
140 |             allocations: Vec::new(),
    |                          ^^^ use of undeclared type `Vec`
    |
help: consider importing this struct
    |
1   + use alloc::vec::Vec;
    |
```

### Repro

Check out https://github.com/mcclure/pocket-riscv-rs-bug/tree/z_bug_rkyv32_0.8-pre (branch z_bug_rkyv32_0.8-pre) and run `make`. This will require rust nightly. You will get the errors above and others. This is my actual project code. 

### Smaller repro

The above example is "weird" in several ways so a simpler repro is to simply run `cargo init ABCDtest` or something and add to the end of the generated Cargo.toml

```
[dependencies]
rkyv = { git = "https://github.com/rkyv/rkyv", rev = "e86ed9c746c280f43d2d5f0265c35f67adab1f2d", default-features = false }
```
or
```
[dependencies]
rkyv = { git = "https://github.com/rkyv/rkyv", rev = "e86ed9c746c280f43d2d5f0265c35f67adab1f2d", default-features = false, features = ["alloc"] }
```
It fails both with and without alloc, but the set of errors is slightly different. I don't know if "neither std nor alloc" is intended to be a supported configuration.

**Comment by djkoloski** [comment]
`main` should now compile under no-std no-alloc as of 7683cb2844e098bc30c793e8851cb9eea7e19844
