### ISSUE TITLE
Update `ahash` dependency to `0.8`

### ISSUE THREAD

**Issue by leontoeides** [rkyv/rkyv#472]
rkyv's ahash `0.7` dependency is breaking compilation on the latest rust nightly. If rkyv were to upgrade the dependency to `0.8`, it should fix things

https://github.com/tkaitchuck/aHash/issues/200

**Comment by djkoloski** [comment]
From #458:

> Unfortunately rkyv publicly supports hashbrown 0.12 specifically by providing Archive/Serialize/Deserialize impls for its types when the hashbrown feature is enabled. Since it's not a totally-internal dependency, updating it is a breaking change. Hashbrown has already been updated to 0.14 in the main branch (0.8) but we can't update it in 0.7.

There is a [branch you can point to](https://github.com/rkyv/rkyv/tree/0.7-hashbrown-0.14) if you just want to bump the hashbrown/ahash dependency.

**Comment by djkoloski** [comment]
Closing this in favor of the linked issue
