### ISSUE TITLE
How to serialize borrowed str?

### ISSUE THREAD

**Issue by AlexSherbinin** [rkyv/rkyv#473]
Is there any way to serialize borrowed str?
For example:
```rust
#[derive(Serialize, Archive)]
struct Foo<'a>(&'a str)
```
This struct willn't be able to be serialized with `rkyv::to_bytes`

**Comment by djkoloski** [comment]
You can use a wrapper type to specify how it should be serialized. See [`RefAsBox`](https://docs.rs/rkyv/latest/rkyv/with/struct.RefAsBox.html).
