### ISSUE TITLE
rkyv/0.7.44 fails with bytecheck/0.6.12 for `bytecheck::Error cannot be sent between threads safely`

### ISSUE THREAD

**Issue by mkatychev** [rkyv/rkyv#475]
### Updating to latest rkyv produces the same error addressed by https://github.com/rkyv/bytecheck/pull/27:
```io
error[E0277]: `(dyn rkyv::bytecheck::Error + 'static)` cannot be sent between threads safely
   --> src/lib.rs:349:33
    |
349 |         rkyv::from_bytes(bytes).report_as()
    |                                 ^^^^^^^^^ `(dyn rkyv::bytecheck::Error + 'static)` cannot be sent between threads safely
```
---

* I'm unable to find bytecheck/0.6.12 to submit a PR, is there a commit hash I can use to do the change?
* This issue is also present with rkyv/0.7.43
---
Reposting https://github.com/rkyv/bytecheck/issues/37 here for visibility @djkoloski (sorry for the noise 🙇).

**Comment by djkoloski** [comment]
No problem! I responded over there, closing this one for now.
