### ISSUE TITLE
Document compatibility of archived data across versions

### ISSUE THREAD

**Issue by janrueth** [rkyv/rkyv#477]
First of all, thanks for this awesome crate.

I do wonder, and I could not find an issue or anything in the book, what expectations should one have in regard to the compatibility of the rkyv'ed-serialized data across different rkyv versions.

Say I've serialized something with rkyv 0.7.43. Are there guarantees that (assuming strict layout and no changes to the types):
* I can deserialize it with rkyv 0.6.x (minor older version)?
* I can deserialize it with rkyv 0.7.42 (patch older version)?
* I can deserialize it with rkyv 0.7.44 (patch newer version)?
* I can deserialize it with rkyv 0.8.x (minor newer version)?
* I can deserialize it with rkyv 1.x.x (major newer version)? 
* Should I assume no change in the serialized bytes between different versions?

The question is essentially motivated by how I need to manage the storage of rkyv'ed data (do I need to/should I refresh serialized data) and how I need to manage rollout of rkyv updates to different components of a system.

Thanks in advance!

**Comment by Alxandr** [comment]
You should definitely expect changes in the serialized bytes between different major versions I would think. Pre 1.0.0, I would also assume breaking changes in minor versions. Note; I'm not speaking authoritatively - but anything else would put a hard limit on modifications to the library. I'm fairly certain that 0.8 is already introducing some breaking changes to the serialization format.

The thing you have to realize with zero-copy serialization like rkyv is that what's basically contained in the binary data you get from serialization is just rust structures being transmuted to a byte array. It's less like a serialization format, and more like a ABI really - without the function calls being defined as far as I know.

**Comment by janrueth** [comment]
Yeah, this is what I had expected somehow. I think it would be valuable to somehow flag incompatibilities between versions in the release notes (and generally document what to expect).

**Comment by djkoloski** [comment]
Documented by e5b2779af8f207d99f093bd486d3004311224c5f
