### ISSUE TITLE
[bug] derive(CheckBytes) fails if bytecheck is not a direct dependency

### ISSUE THREAD

**Issue by Alxandr** [rkyv/rkyv#485]
I'm not entirely sure how to solve this - but given that `rkyv` exports `bytecheck`, it's very natural to use it's derive macro. This fails though, because `::bytecheck` is not available.

**Comment by djkoloski** [comment]
You can now specify which crate `bytecheck` should use with `#[check_bytes(crate = rkyv::bytecheck)]`. When you add `#[rkyv(check_bytes)]` to a type deriving `Archive`, rkyv adds this attribute automatically.
