### ISSUE TITLE
Archive schema update?

### ISSUE THREAD

**Issue by XavDesbordes** [rkyv/rkyv#486]
Hi,
Say at time T0, Ihave the following struct:
```
#[derive(Archive, Serialize, Deserialize)]
struct A {
        a: u32,
        b: String,
}
```
Later, and at T1, I decide to add a field:
```
#[derive(Archive, Serialize, Deserialize)]
struct A {
        a: u32,
        b: String,
        c: u32
}

```
Doing like so, I get "attempt to subtract with overflow", which is kind of expected.
Currently, the only way I found is to add the struct version in the name and have a conversion function:
```
#[derive(Archive, Serialize, Deserialize)]
struct A0 {
        a: u32,
        b: String,
}

#[derive(Archive, Serialize, Deserialize)]
struct A1 {
        a: u32,
        b: String,
        c : u32
}

fn convert_a0_to_a1(...)->A1{
      //deserialize A0, reserialize to A1 here
}
```

Is there a way (attribute or anything) to avoid this ?

Is an attribute possible, like:
```
#[derive(Archive, Serialize, Deserialize)]
struct A {
        a: u32,
        b: String,
        #[optional]
        c : u32
}
```
that would not cause a hard error if the field is not present in the calculation (but I guess that would really make the code more difficult).

Thanks

**Comment by djkoloski** [comment]
Schema evolution is discussed in #164. For backwards compatibility, take a look at [`examples/backwards_compat.rs`](https://github.com/rkyv/rkyv/blob/main/rkyv/examples/backwards_compat.rs) which has an example of how to provide backwards compatibility for your archived data.
