### ISSUE TITLE
How is deserialization performed when rust makes no gurantee about layout of its structs?

### ISSUE THREAD

**Issue by navneetankur** [rkyv/rkyv#497]
From the docs I can see that deserialization is just a mmap of data.
It should work fine for repr(c). But for repr(rust), doesn't it mean, we are making assumption that data layout will remain same across different run of compiler. Rust does not guarantee this as far as I know.

**Comment by djkoloski** [comment]
1. You can enable the `strict` feature to enable stable data layout across compilations. This is recommended when you're using rkyv'd data as a storage or transmission format and may need to recompile and use old data.
2. This is one of the reasons why the `archived_root` function is unsafe. If you check your data with `check_archived_root` then you will catch any layout changes (though without `strict` there's no guarantee that the data will be exactly what you expect - just that it will be valid and not cause UB).

**Comment by navneetankur** [comment]
> without strict there's no guarantee that the data will be exactly what you expect - just that it will be valid and not cause UB

I didn't understand this sentence completely.
Though my initial question is answered that serialized value should not be used as storage format without 'strict'.
Thanks
