### ISSUE TITLE
Deserialize from str

### ISSUE THREAD

**Issue by amab8901** [rkyv/rkyv#505]
Serde has this functionality:

```
use std::collections::HashSet;

fn main() {
    let var: HashSet<String> = serde_json::from_str("[\"hello\"]").unwrap();
    dbg!(&var);
}

``` 

Do you have something similar in rkyv? I couldn't find it

**Comment by amab8901** [comment]
> As far as I know, serialized rkyv data may not be valid UTF8, so it can't be stored as a String / str. So I'm not sure how this suggested `from_str` function is supposed to work, maybe you could elaborate?

maybe it could work similar to Serde except replacing owned items (e.g. String) with borrowed items (e.g. &str) as you do elsewhere in rkyv. The purpose of this is to be able to completely replace Serde with rkyv rather than having to keep them side-by-side. I'm imagining that rkyv is to Serde what Rust is to C++.

**Comment by djkoloski** [comment]
rkyv has `to_bytes` and `from_bytes` for this kind of functionality. For the reasons @w-flo mentioned, rkyv can't support `to_str` and `from_str`. You can read more about why rkyv's serialized format is different [in the book](https://rkyv.org/zero-copy-deserialization.html).

rkyv will not aim to support a human-readable text format.
