### ISSUE TITLE
Specialized `ArchivedBytes` type to support inlining for string-like `Vec<u8>` data

### ISSUE THREAD

**Issue by swwu** [rkyv/rkyv#508]
Recently, I've been doing some data work involving a lot of not-quite-utf-8-strings. Due to the nature of this work, and the fact that most strings are small, I found myself really wanting a `Vec<u8>`-based archive type that does inlining similar to `ArchivedString`.

It strikes me that `ArchivedString` doesn't have very much in it that actually enforces or requires string-ness; it's pretty much just taking `&str` in some places, returning `&str` and `&[u8]` in some places, and then checking for utf-8 in the validator.

My proposal is to introduce an `ArchivedBytes` type which behaves identically, but takes `&[u8]`, doesn't allow getting a `&str` back out, and doesn't call `str::check_bytes` when validating.

For my use case, I actually ended up writing a really thin wrapper around `ArchivedString` to get the inlining i needed: https://gist.github.com/swwu/6313b5ecaab2a0a74c1014f62573f3ae

While obviously a "real" implementation wouldn't use this exact strategy (e.g. it would be preferable to define `ArchivedString` as a wrapper around `ArchivedBytes` instead, due to the former being stricter than the latter), I feel like this is a decent demonstration of how close the two types are in terms of functionality.

Happy to toss a PR together on this concept, if it seems reasonable.

**Comment by djkoloski** [comment]
I think something this specific would be better suited for a crate that builds on rkyv. If you wanted to contribute your type, I think [rkyv_util](https://github.com/rkyv/rkyv_util) would be a good place to contribute.
