### ISSUE TITLE
[Feature Request] Introduce a "standard" wrapper type to pass around archived types in an owned (`'static`) way

### ISSUE THREAD

**Issue by swwu** [rkyv/rkyv#513]
It would be nice, for various reasons, to be able to create an owned object which can be used to resolve a `&'_ ArchivedT`. In theory, you can do this by just passing an `AlignedVec` around, and just resolve it whenever you need to use it, but in practice this can be a bit finicky—either you have to constantly re-validate it to be safe, or you have to play fast-and-loose and keep the types in line by hand, without help from the compiler, by resolving it unchecked.

My proposal here is to have a struct
```rust
pub struct ArchivedWithBuf<R, T> 
where R: rkyv::Archive<Archived = T>
```
that basically wraps a `AlignedVec`, can keep internal state about the validity of the held bytes, and exposes a
```rust
pub fn as_archived(&self) -> Result<&T, ArchivedWithBufError>;
```
to allow easy (and hopefully safe) resolves.

This is an actual implementation I threw together for this, which seems to work well enough in practice, although it's a little bit rough:
https://gist.github.com/swwu/a92e29fa4c0fb110939f74fd896647a1

Happy to PR something like this as well, if it seems useful.

**Comment by DiscordJim** [comment]
I opened a PR for this in the new `rkyv-util` repository. [LINK](https://github.com/rkyv/rkyv_util/pull/1#issue-2451761269)

**Comment by djkoloski** [comment]
After kicking around a few ideas, I've decided that rkyv won't ship this out of the box. Instead, you can use the impl provided in the `rkyv_util` repo linked above.
