### ISSUE TITLE
Deserialization / Documentation Problem

### ISSUE THREAD

**Issue by moberer** [rkyv/rkyv#522]
While trying to deserialize a simple archived Enum with this crate, I ran into some issues and wasn't able to actually get it to work.

In your documentation you state:
```
/// // And you can always deserialize back to the original type
/// let deserialized: Test = archived.deserialize(&mut rkyv::Infallible).unwrap();
/// assert_eq!(deserialized, value);
```

However, this does not work for me!

I have the following struct and deserialization implementation attempt:

```rust
#[repr(C)]
#[derive(Debug, Archive, Serialize, Deserialize)]
#[archive_attr(derive(CheckBytes))]
pub enum Value {
    Integer(Int),
    Float(FloatType),
    Bool(bool),
    ...
}

fn deser(archived: ArchivedValue) -> Value {
    let deserialized: Value = archived.deserialize(&mut rkyv::Infallible).unwrap();
    deserialized
}
```

However, this does not work like the documentation implies it does.

When I try to get access to the contents of the weird "With" wrapper type, I get the following problem:

```rust
fn deser(archived: ArchivedValue) -> Value {
    let deserialized: Value = archived.deserialize(&mut rkyv::Infallible).unwrap().into_inner();
    deserialized
}
```

I get the following error:

```
error[E0283]: type annotations needed
  --> larve-bytecode/src/datatypes.rs:63:10
   |
63 |         .deserialize(&mut rkyv::Infallible)
   |          ^^^^^^^^^^^
   |
   = note: cannot satisfy `_: DeserializeWith<ArchivedValue, Value, rkyv::Infallible>`
   = help: the following types implement trait `DeserializeWith<F, T, D>`:
             <AsBox as DeserializeWith<ArchivedBox<<F as rkyv::Archive>::Archived>, F, D>>
             <AsOwned as DeserializeWith<<T as rkyv::Archive>::Archived, T, D>>
             <AsOwned as DeserializeWith<ArchivedCString, Cow<'a, CStr>, D>>
             <AsOwned as DeserializeWith<ArchivedString, Cow<'a, str>, D>>
             <AsOwned as DeserializeWith<ArchivedVec<<T as rkyv::Archive>::Archived>, Cow<'a, [T]>, D>>
             <AsString as DeserializeWith<ArchivedString, OsString, D>>
             <AsString as DeserializeWith<ArchivedString, PathBuf, D>>
             <AsVec as DeserializeWith<ArchivedVec<<T as rkyv::Archive>::Archived>, BTreeSet<T>, D>>
           and 38 others
   = note: required for `ArchivedValue` to implement `rkyv::Deserialize<With<Value, _>, rkyv::Infallible>`
help: try using a fully qualified path to specify the expected types
   |
62 |     let deserialized: Value = <ArchivedValue as rkyv::Deserialize<With<Value, W>, rkyv::Infallible>>::deserialize(&archived, &mut rkyv::Infallible)
   |                               +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++        ~
```

I've also tried getting something to work using your "SharedDeserializeMap", though still without any success.

At this point I'm severely confused. - After all it should just work like in the documentation?

Kind regards, and thanks for your time and for your library!

### Used Versions
- rust 1.80.1
- rkyv 0.7.43

**Comment by djkoloski** [comment]
This is a bad error message from rustc caused by a specific arrangement of blanket impls in rkyv 0.7 (these have been changed in 0.8 to work around this issue). You may get a more helpful error message by using fully-qualified function call syntax:
```rust
let deserialized = <ArchivedValue as rkyv::Deserialize<Value, rkyv::Infallible>>::deserialize(
    &archived,
    &mut rkyv::Infallible,
).unwrap();
```

**Comment by moberer** [comment]
Thanks a lot for your help!

You are right, this made the error message actually readable!

By doing this, I managed to track this down to a wrong manual serialization implementation.
(I had accidentally implemented Deserialize for the source type, not the Archived type).

I'll close this issue with that.

Thanks again.
