### ISSUE TITLE
Alignment Issues

### ISSUE THREAD

**Issue by TroyKomodo** [rkyv/rkyv#526]
Hi I was looking to use rkyv as an alternative to the `zerocopy` crate using `sled` to store data on disk.

https://docs.rs/sled/latest/sled

Sled shows some examples on how to use their code with zero copy however their alignment is always 8bytes. This seems to cause issues with rkyv and makes the operation unable to deserialize with validation.

Is there something I can do to relax the alignment restriction from 16bytes to 8bytes or is this just a hard requirement to take advantage of rkyv?

**Comment by TroyKomodo** [comment]
https://github.com/spacejam/sled/blob/main/examples/structured.rs

**Comment by djkoloski** [comment]
Reading through sled's example a little more closely, it looks like the zerocopy types being used are unaligned. This is equivalent to the aforementioned `unaligned` feature in rkyv, so I'm going to close this issue.
