### ISSUE TITLE
Using with on a Vector

### ISSUE THREAD

**Issue by CoolSlimbo** [rkyv/rkyv#533]
Currently, attempting to use a `with` attribute, on a `Vec<T>`, where `T` implements the With set of traits doesn't work.

Is there a particular reason for this, or has it just been yet to be added?

Example:
```rs
#[derive(Archive)]
struct Test {
    #[with(AsString)]
    paths: Vec<PathBuf>
}
```
Results in an error.

**Comment by djkoloski** [comment]
You're looking for [`Map`](https://docs.rs/rkyv/latest/rkyv/with/struct.Map.html):

```rust
#[derive(Archive)]
struct Test {
    #[with(Map<AsString>)]
    paths: Vec<PathBuf>
}
```
