### ISSUE TITLE
Can't find ArchivedAlignedVec

### ISSUE THREAD

**Issue by jsonmona** [rkyv/rkyv#552]
Documentation for [AlignedVec](https://docs.rs/rkyv/latest/rkyv/util/struct.AlignedVec.html) refers to something called `ArchivedAlignedVec`, which I could not find.

The documentation was added in #280.

It might be worth to clean up the documentation on how to archive an `AlignedVec`.

**Comment by djkoloski** [comment]
Fixed by b950d87e716e640e475d87ab5678e8b303973668
