### ISSUE TITLE
Rename field while serializing ?

### ISSUE THREAD

**Issue by ThomasCartier** [rkyv/rkyv#558]
Hi,

Given the following struct

```
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize)
struct A{
#[rename_to="my_field0"]
 field0 : u32,
#[rename_to="my_field1"]
 field1: u32
}
```

Is it possible to rename the field while serializing and get the original name once deserialized ?

Like [Serde does](https://serde.rs/field-attrs.html#rename)

It's useful to hide some struct logic to the world, when sending the data in conjunction with Skip. You don't have to create a "networkable" separate struct by hand.

Thanks!

**Comment by djkoloski** [comment]
rkyv's wire format doesn't include the field names themselves, so this would just be a rename for the fields of the archived type. Can you provide a more complete example of how this is useful with `Skip`?

**Comment by ThomasCartier** [comment]
Ah! yes, if the names are not included in any way then it's fine as is, I can keep using Skip.

Sorry for the inconvenience!

Thank you,

Closing
