### ISSUE TITLE
Update to 0.8.9: #[archive(repr(u8))] equivalent ?

### ISSUE THREAD

**Issue by ThomasCartier** [rkyv/rkyv#572]
Hi,

the question is in the tile.
I have a bunch of `#[archive(repr(u8))]` and in the 0.7.45 and I decided to update. But this is keeping me back.

What is the proper replacement in 0.8.9 please ?

Thanks

**Comment by djkoloski** [comment]
Archived enums should automatically be set to `repr(u8)` by the derive in rkyv 0.8.

**Comment by ThomasCartier** [comment]
Nice thank you!
