### ISSUE TITLE
Backward compatibility with differing rkyv version but same schema.

### ISSUE THREAD

**Issue by ThomasCartier** [rkyv/rkyv#576]
Hi,
If the structs to archive are exatcly the same but only the rkyv version change, is it guaranteed that the newest rkyv version is able to read exactly the archive properly ?

For example, I have an archive made with 0.7.45. Now, I upgrade to 0.8.9 and open that archive.
Is there any corner cases I need to be aware of ? The archive is stored in a database.

Again schema structure untouched.

Thanks

**Comment by ThomasCartier** [comment]
Answer is here https://docs.rs/rkyv/latest/rkyv/#compatibility

Closing

**Comment by ThomasCartier** [comment]
This is the semver compatibility that bothers me.

Should we expect 0.9 to be compatible with 0.8 and so on? Will it be written somewhere that the archives are not compatible anymore?

**Comment by djkoloski** [comment]
> Should we expect 0.9 to not be compatible with 0.8 and so on?

If an rkyv 0.9 were ever released, then it would not be required to read data serialized by rkyv 0.8. 0.9 and 0.8 are semver-incompatible changes, and the compatibility guarantee only covers semver-compatible versions of rkyv.

> Will it be written somewhere that the archives are not compatible anymore?

The compatibility section of the crate docs covers this case.

**Comment by ThomasCartier** [comment]
Thanks a lot for your clarification 👍
