### ISSUE TITLE
How can I ensure the serialization order？

### ISSUE THREAD

**Issue by xxxmailk** [rkyv/rkyv#579]
hi,all 
      Here is my code ~
`#[derive(Archive, Deserialize, Serialize, Debug, PartialEq)]
struct Test {
    a: u8,
    b: u16,
    c: String,
}

fn main() -> Result<()> {
    let test = Test {
        a: 1,
        b: 2,
        c: "teststring".to_string(),
    };
    let bytes = rkyv::to_bytes::<RancorError>(&test)?.to_vec();
    println!("{:?}", bytes);
    Ok(())
}`

The result of serialization is：
`[116, 101, 115, 116, 115, 116, 114, 105, 110, 103, 1, 2, 0, 138, 0, 0, 0, 243, 255, 255, 255]`

If short string in struct, the result of serialization is :
`let test = Test {
        a: 1,
        b: 2,
        c: "hello".to_string(),
    };`

Result:
`[1, 2, 0, 104, 101, 108, 108, 111, 255, 255, 255]`

How can I tell rkyv keep my struct orderd when serialize ??   

I used it to scan keys in tikv with prefix....

thanks~

**Comment by djkoloski** [comment]
rkyv's object ordering is documented [here](https://rkyv.org/format.html#object-order). The root of the buffer is located at the end, and you should only ever access those buffers starting from the end. The `access` and `access_unchecked` methods calculate the root position for you.
